sprite $R [120x120/16z] {
x9O7pkim38ChRyiIxt_SXpBed-dcxKtiGEXNKnBjnsVhlqH-2PLa-TdKNt7e8ohy2Yeblu3vmz7o2mPSSjToqyVOR6JvhjIgPG3GAFC_Pe2bXyJmtQ0rFN4X
3y1xlAh9ms5v8ShtG4ik6tj37O3L0perXxNjHudXc_mEMaz_f07mjOrI7D2B0wRubT1OysKx9LM7Zq9_rQ5vOci8NuuEgUR7LEIXqz-tlGpnYtOhMRehbmJG
uDkfR9z9ZYahNCkRSWxOA5d1WPgN5GL6o-d-xwKid1u3-kJG8O-Nlr8D63bSjqe1r_nKAVBMttMG93J0zNoOR40FcxeAOAIJQyC1BVb3PUABX11EsUYmblPV
lDEHumBxjYurexy7dUsUnbinm4jOIZfWPUBK0Bo6nG07lEShrTLGbiwdNKBn9ovsXxsx6HYZLfk1_avLqikxA7ThfG13_qQHTTxoUzNw_AK6ZBTaYGE00sZX
RLqsmEqEp8kD6G70DRrDfYGIYs4UJrA6mtl9kJJMJQ3gT6InfnDTJ-ig7DJ1tNiLNiMnfEvmhUkl6w3r16tazBG-18E2Q3dTFEM0K01ZHvOEmCe1mhhjn-e0
C29nkzNaTwBvPZdVj6kXzVXOwqOh-QpAk2gPQewDLU7O8sPzOYlvqzDcSgcuEgvvgcOERwLq1wp9_C4jnK4n2U-6Txgf9tk1NK9SdIWrSkyUXebjyNx3RSC1
zCEsN3i9SDhhzCYCGcjBrqo7MPri3G0VG7Xy7ZS8eyVguqgLJMC4EAZB5gjZkIFzixcyWhdZckLqao-Roc6Xt4-NJ-d6vI3WYxXKyTs8qOLHFj9kaUTSRRUj
TSa7qhwSIstICQbZr3KLiCYM0pvP_aHNci-tofHx6SgoSjTeq6Qmlkx67hkceplMjzctSAdGjpugLlaf7DTa_KOkvV1NwXasAeTHSiJ7z-KkZVFMkke7kcsk
6jvS_REuUS9zN75VK-mj-xwvd5_ZnkaFuJBu3isb3Skc_ZWkjLoO2cWk_LErTgBaA0y30PYMpOtr_c_x_xjDgAuT834Ek6eqz_dDePYs75S8UTXLFqyANHNS
xY-vBfFAy1NSj5q85dw_4hShS7jtz_xCdRFT67797Td8txY8qvhR1rnmjLoKkUYTW34qzCXqsLLTgOj-TlUnqvw08JF3dVXdBd8HnrTIrkUiNMgVtRdKnSY6
nC_hVkZNq7peWYunTlDbrxXVYyTv8qxSwhvp-NTfhxhzx6bkt-GSn8MhqRdhxzrbx_9B5dpALw5tBO0VN7noqJ9rzY4lr_62EWGKkne9UPgIeybpj-78WBsh
J9NUkXYOsoEQ9T_LCAYp4jUOJ6OEUAwvhC2lZjZzdT-wY3DRX1yjSZNiotMJznDpEvkZpDKCL6ioXrJdRaZi9Aw_vQwAjorjDa_SZghGObULd05vE7NHCLUo
htQkVU5o_yFnqDxbbOQB-tYxgmWxoTKGoYVcoYTS5jjr6RlDvMvHs_DCjoW_zpF7Gbtoq2qQHppjQlkdeNWbTz_FSYt3ZPNSSE2sdLLs4KVDlQkv69o0TGld
tbLSS2x0-07EipdqnREkjTCwzcQ1pstcalwWkrxBmsRoIJ_DrE4HD-g4GEvMnZLllDyT5WqZTguYe0ztkfts9tjNXTOLoRvrrw6kAuplNPKxFtkEfa_CTfE-
265awfbtVmCxSKC3vhavbhjXJAzxV4mNt2tFfI6YmENcqjUvx8cxA_YFp3yOBhdebEyAN1R2m8bSjkjhAj3fTfchdXowpox2xBghmRaRCbpT1fSk9pzFGefT
LVBrBAW_SZMfMTBH323RjGENftqy8TkxNDjvgPaVS7L2ixh-SkFistspdd5rZB2CgxiD4YQ6fGTT7PRFlNiSaclOb-_68fUqlohrXfrHccDnwghwIRczcgjv
pkzp0THr0UMiUYvH5L3kvi-zJOmADxZB6nT2VyfGRh_RjMDKz96BBrsSepAcTBEx69gIAdVLiNLT4AtimjZ7bLt6WCekp703Ui5D7e1epKs5ETjjWUR62Y5-
TitQsr0LFhWXDa-LnJCt69ed2o7kNC2igL3XNzVGr2g4bmkWagekMjpgeafAlwx-1m
}

sprite $R_ [120x120/16z] {
x9PPWkGe34H7O3OXlVlVTcQQDDbEbt7lUyUd2tYbK23odvzTVoK_Z2a_0ltToV8Zq7BvJRurzKVuBV83yfsqv_iLePhbhykEgHPrQBA4fextB1A_dkD5exop
SRCLENRmMQjiuSkPad8AB-TRZITeDQmSFqe8NuIMc6juqqJeARptrt3TBhO6-LngBLTx9LIW3zJMeMyBWCJuwT2GKfAr-StnLerURi_-HBzbw-L3Imf0-w2P
ePIFzJlcnvsufHgMjf4okLcMksCbfmz3Gzp2db5lrqw7h3FKeNJG79RDCCtfV-KKvRRK0odebP4IEsWufiz1utdPsDrpUYfdMK732H8s1Ml7QjJHBPpJKC5R
F9pK37h9wQnmSJkkpIeTUexx-TwlKo9PVSwEM0nCqwLEVj_6iWA-IGNkKfuSF1M0dcuqRvxaDNKQsPYZuawn0bXD7rBTHZblM_QspMxWjqCYf0vcZjLyMwy2
kp-WAt9KHbv5YiDo26m6tiQv3bPML0MWFVPKOtzdJjgQpVivWwjPhiUcFbcv6TvFTk_V6MCXF07gW1rRBV7ndv-gTsZ7K4gi5mNcxg3vnTyEU4-Z9yVmA0Cj
xyU1Npn84XMyJGlgqjMiu9eFK6nUu70QWFtXGynZycxBiQlGInZhhUMKyYAtZxyNTNXvkiBREU4CzKLqJ-lwNajB2pM6lBqO5wzUwmAWizYxcEDQZOU3rohT
cO5OSgT0HzVY4beCQwEOgKkeEhZ2oTOrLyOlE3p9LNTzlwcPfspXiFyVN_y4xfW_8v2dDpjtz_R8R-SXT-Zr13McOv_AdQ-HrsTtPCDxsKq4vZYktK7Boqsr
DXBowTpfAlCT2WrosbKPyYVB0HqJ0-OFWINtChG2yhAe66WrUZrZsyiKTB3_ghCJtLXv60h0s5aWaFZzt_PV3Zfqk4rfs2BTT6zdvbCZ2qxibGTqrzrk3b17
VAeMKvoDGUyP5qysL5bOKWW1x9-bLF1RDmpNtQ7ov33DnN8o2m72-676QS66Q6fpmncN-viosLtzujOyl-AoMi5kQE4Dz3qNMumrZxmICZ2ywwugz9Jm6I_Q
oQMTS0RjuAQDdKF6wrrourataqsXwYxjhlSdNB9BkEFw1RczZ4xEkILSTrtC03IPMOcdt7ZPZHcxjK9XZPpIwaxXaejyRqlKmNqs3f2_MjmSBhY2Krj1Nmek
PHsHDxNgocSzn_CkyhqnkT3bMlTXF73HkWfdtN5DQdAGSo8kWLxgBZPwEd3pDrUSiMwFyvMBnXnPTqEpo_DUT8svRisHNhwxnSOlLmvTGJ0hSp4P6jrX42It
KVvq5mjjhiI2qX-6VCR5AHjL9ZitvSqjFxkoHX3ixpcNpVs2MFhbXlYhgnwv4WsjQowRx3RxpGs7Rh6rWp4Zzznmj-EunGRN5Tjo-rqNz6He_1sw6lAMAvzn
iO4epvzTe8Nrl7VrZhksX-Qnuk96WuP8Ujv5CIFCnG-NyuOouxNUSNdsAcbpTIh6HkDDLuvST8Tmm8_5V5nGRtZTbrsUihbmxEpauWIOUUlewDQl6t2rnVLz
N5TpmoYzNJ-ptowTNBQNjnlqh7tS4RbIrwcydtXyVjL5_tYRmgsVFTe5GLzpnIMqspUJJrQ_u0-lk9eAnzLx5yiXHwR7tRImtLvpiJGXyCfZhdZZFEB0vGEP
8--w0VrsLDAXozoUoZucIQjR-1m6uP8grqcjkcWohZbIBxioSJmorzsXwkAWjA1zVS7LAJDNjhi2bmDajElbZAkxD739vS2yZCrkpDl1wexB0OTPQd1TDWxQ
3btNuduLoNZeQimSUDrtkOfjXvMw2zHAhVVGxch5nPYHmNtl2jEjB2-uiD0BYlZUJ3YOtQR_RxaXJWMbGnU3QDvftdD1p-ZrJMPXollSNdVlpN7sO_HgRg-x
-JaNemNczhuk-pb_eIkTNL4sXgMVAw9xxORRtcyNVhkJvRQRZrmH6UfBs6z_s3r4ITTSkUdg4KeZbMVTHOSBwwwB_UtgqkpioWrLBhkEttJyVyMfFA8skyMS
YDFXgQNDRWJwt7BE_-gA1gWFB_N-m1LnChorVdJL3QykSVwxgyBlUj1qcHwwq7GLTiUbFjkT_VqN
}

sprite $L [120x120/16z] {
r9O7bYCX34GDZOZIl_zjD-XvsgRZvb0lJP3vKAY47_-RWeWiuKz3boIkz0VH8SgxKlmZr9XagoJXTqEN7VKF-BtiS7_0Ryb9RfHx-iNGL0PeArVGPbXByTUT
EfIHHQG3La-enK35ovVbrq1RoH-BTq3tw38CpV4jQ3-93gcqF27gCEZb7TeCRTkBZJ7yEBLrEL0reB_vEvQJeFzGKaifSg9S5RJdCemXyNpZuJjJ7LEjNzVF
5v4nW1vl1_ctevS1GwGRoAawAExnfR91ZTy2_NhAEi2b9r5LHbaU8TMvfsQ5t8sHuzV-NkxwLtnTFdG0BOgrTHqPXkMzcI4riBOUzMA0fxnQ-DG-hKMXpHa9
eg0vJAvrWpwZmfAkdhUY7yYMIpTihEZQZJu3dfYYM9VmF6bLtDyz9CQDAMldDd2DzstqB98xM3cFG3TeIuZ5mDg9gTCKJKbM3LmjRz9gXfKOhYFJmN3wPLrq
TBDMDbWh-p41FSURA6IlQodSV25ibXyFmv-P_Z9vpDJXCKq3xvJpA2XOVeG6LixBGWMeZyVpDFGdrihcfQ4dFsWKVuCFaoZTiBA4DK7Z41sTPVMh8zuowcJ7
vXUqssQ1M0QCFADzUbXFqyGOHfSuGwN3g-tpb5bx6uI7XhbF-WRntvU3OJM_LCjW-k2JouVKCzCKhAI9Ef-lfTVvuqb_5ttMfQPCHeKdDtzG3L35VRjGylli
e2tUrbNbLJXp6wwHd-FASt-J1W2vhKi6K3twU-vWLIa0vlFmL4jLUgw6rdG5zP43ljGHLrTibGon6L1FqXf5qH9Uhz7n78lPy0S37hVSwdVzjIcg9ss_OjPf
OaPHV1VxCl0jNN5jnJftdMVpTFG_MKjxq-Uw81tMAxZdCkJ5TIK5UWnU6nkCT7pV7HYUky_jseU2f20G150R2IBO__-vvzQCLnTS1aRX8XSt-IOGYaQPep80
LRdPqUMwd308JCp5x6ZiYjw8aOgPjTxr9-unEwZ6bzanu38fu1lhtUZENBGP5op3Wgjix64LBZgVAxd9PorcnxIhoRtXhaLttV-A63AVP4TD7pcvqKtAo1hE
tQDBOtN_jWbNhcOtggulNOvgpA8SkvahLwFhLKEDowoExEYnSc6ajhc6ww-ZkvLSDB5f5vcutdRNqEHYLAjw85TSi2qkhWVZakk6ktbTQjnudpk777SNMu5X
Bl8zSZjYyWQwksiHoH5G7jKXp7E-hpkZkBPy37Uuh0vb3pTNkbkBwp7S1P-2om8ONk_GmKMbuzYuq2MDtAxRhQvHLKQ_CnVqu_M-oqKTW07qnAMitBRHNHfT
hbRA_bTqlQg4pDpUxZ9Pu_NLRQfpz-z3VOJr9zliklprzLMjTj5O3sfoZyH_1Fn6bxlbD4kBQnPL1lntNERnNEsYMig0t-wo2Gur_5nmMS4uPiBBBdDxjWNt
g61iUARtkQjBnwW-SorwqcBnkJlTYEeJhYrqMHPzPjihRc5T44ncYz1zBZGRNeWkBgj8sFF15O-U5D2JUhfezjY3hShStjj54tJUqzm-lUNMvmqJTCCSEjYT
1D_tMxjoukOZHz9DVTtPfsLtaMk6kCpjOPg2nnINmWZNCbVwevo_HT_LbJcmVWyNe_PH-U_dOZfze7HvJfIM3gxnYIiAtHzFTPFSwSep5qziT4adLeNkS57A
HiMqx28_i_vxnMLkvsVABbOSpFaNNERsUXUdOrpZMbtMsp_FxUSkQt6BRNMHsrblRtLPU_HYwrqnaNSwjBkSJv5agbtDF8fjSuFgIMxNwEILQrnKtHAgU9TT
vdQDfkIQLLbllyrDBd8FGfUv_L4wvpYwoLsFMdvsCrqUVAfcrDllTtbsaHrTdA9mfUdaSbFYP7TnnCELfgUBZv1GbcTkvmwxiyl3EAuqGrmqyQeu6HliObzs
BRUFTmtlUHtdYiZ1st6k-Nwo9RrqT8sStiFTrHMylkVDTdF5lBgp-g8h9owVQQcvzLut-QcrNNVnJ4Ux0dMiAtBbrc-Pq6ohAzVlxsztZJ6tgDBa6diPfR74
EXSxsAuDRk7srs4kxdmTxHgCrB6kY95195qkD0EVBvVKaMvErUZ_zWK
}

sprite $L_ [120x120/16z] {
r9M7Tkmm24GDwXBC_t_kEsYzMdU_z8Hq7y8L0oDFVow8tGzGdGyX-C3V2cKNHhXlG_kmYM_GcqpVVVWlHHCFw06QleWweD-9vYnIRh15L09z9ZIKaaM1bawX
gGAIUI97duHsBS-b5K0xf5O0vSaZpn_tJ4gB7cCHG6hSwWkKbS34p1_Ij-w4ZLLDq85E3P141uRZT-eTHryxD8mrwwlf343kxQuEoLewZTm0hG8jrmlyDhqv
wrRVurL2lXEJN4l_fpV5bCH6U0MrZEnyixoBigwgpS7vMwWByLaNeXRrmAhsjEFOrgf6FhP2dyFZ09TRnZ4-knaX1_fgM1wrA50TRLNJJHwVR08FOoWMeJMk
JIJHRKNo1P3oUaocWgPT7ZlUwJkeIsYBHOPROnQhVh8KxNaYxehKCT8BL_DeIR2CF1PNKrAWyQNVRIgnsVUhFQBmgEBpovLhXTDoUu5oQqLlK6HtjxpUKfQl
cLZg2nt7GqkHFZ6whARGqXGryENbsu0oJMMUv0pPOejr7caYDgKrdb77LfCDgxapIGJp8BeVyNpDo7AsyrRvLKSrRfhUkzWbsq2_dsmnK7iO8hucgBaFo7ek
8TephMuxGhK9qW9wU6kvekkvc5uTyJnT7CipEbLejh-gfyCRr_wTbkVWmxpwoYEhlZWm3Qx9sc3HZBdIxL3N5jbqlteZKQnMnzcFaRZXRjoRxhpmy9o4wIOI
i4tSSai7feenr_CmuHIGHBTf0CnOvzmkShTIxILFqHIAxMlN-yAj_SQ4PC3-EkLsHNBdpZuJJqVKkl0dPPoubGsAoXFTS9lf6sQkNThju7vtHJOTaZVB5BzB
cwMuvOxROkHnbjNxp4L1ItJyDXfk9Kl3IBpZ5kF6mLteED-Ejku3kaVhx5RxvL_xThRbDWW40LGD68CG_F_dvb1owOmIIGCOU4g_p3ut2qjrs-OtbhY1uO8k
QpyTrnZTSzzb4Cl0cmLLvCRyfwHxTS4ztKOemRS5eEKkzjcDk-ZFZVoS7V4zibIuq59yS5VS9dUdfyOAT4PgNUpUmFUkN2oja2woexBRiUEgNNIIpoxJmlaK
jTYfR3shtL3cubOFF4K5kuz9eC9LXxlzSEEjUzxL_jZRxMueTb6YNKpCyAqkQWt1bhhyVJHQNTPCrziYrtTqnTfbYUX_vhbYF7Bxtkg-fxZCPJdCVk9v3E_X
Bd8HSgLabzEXv6sT6sjSCKXRbkVLAJr7dzsjlulRAk9IERaeXAAmzdVVHvzrwN8w59NqSyKcHiux5xNdTgzxk4XypEtFBfA7tzWk7gwhTNbRRGxhz7VNvk_J
wsbEOUfTGK3DDtMDUynbNlKkSmy3VaerBkTGoHcfSvKDoEr0MznZDReAT-zcsPUtkipZXUlPP9C1lzrbcPL3WWTNzES127pKmSK-YZ7lQdNlxYW-rzFrOXn6
RFh2LNPD-zU-SU_FPnCoRUHmERZXlyK85wLCtjNXzN7P5daDRfJBsvkz49Ow9tX3tVDqwCZjarni6kRsFcvDtjXep7QN2tSfTBqRxyhVSpVazkZjsGqZNNHq
RbaSS-GKLnno9Vfk2pguuIvsFdEbpHOdy0DTv7PEAEZoKTqOx1WNnoddztHPBkIp8FHttSRSS-doeQkefPyhhyJ76UvSr3ujMKqFbxbTGtrqCQ_R9qL6ldAP
sptEgoBtc1GrkkVSNkFYqJ5Eh-jTxN_9xRSkoeQ8dwvoztbxvBozsaN9QpzGobsB7M61jhj7RjzCYMjIukoosdtVpDitgnvTKHQD1T0kBdBx1lhUHMwFM5Sz
tHMz9QP0_xh8xRXf-hlu_HvXMGdT7xaz61WZN21-RmxecZLotZxEHOdDLB0wHRHCl6a6koZiQXGRyWakQZ-Kq1DFTOz-iDLLPhehdmsXpKHNeB9qDrSUNL6t
psbsmrmHkNdchHde4hsc1xdg0ULD7s9dDyXILDBL5RKqLhih-6YoAysgy1rJxtxxgWffSRMIvVkIAbUasqifv5NkzdtfY38bhYWBjNCzko880LDTBj_9hXAP
0PvTKMgPLa9NmPvOS0NgvAfuUSB_-WC
}

sprite $F [120x120/16z] {
x9Q7SWGf34IF72Jr_t_kMJLBgMOCExFnOhk2GoyFOTJYZx-x_fVx-Ve-T6FwBrCFE_WEqtt_m5S4vxuCDRaFCOCxjQJuRgflW1Jlxa1z4KWBxuJM77me0d1n
2sfXe4Ud_E3U0aqbtnQAJHTF_XSqDO1iIzwxLz6Xv_tF1A3loAu2gCUjn1V8iQGmgRy3tC8uNuBK6SIvu9-gD9NVK8E1St2nGoYxzHh-qQfpiu_CqG80Oj0L
Ebo7fWvA9vxO08Rq4t2eBEKIskUQCWcahFiXP8QsL6W2jANFPuPe1V6ijLpEQLDXGEhKL0IIlRkbM0UapPRD371o8-tYkjAGSZBbnW1bVoYXWsiy_WfKzhsb
l-CQTZxltOoQ9ke2K5JxA4uepc-P-imszuNe3j2O5igwHjSrOXTGzAkfKKHzcmsKLZvdQ1VINLK2fF7nB2TfAM2syrtvjguEJ3cTg5xgLUVL1_9dlYJqqwm0
XCeQsbZBBHq0vNj3Yu4UGs5DqJKqam3ugRUGABhDgiwLR5TLZIsw6JIJJQJOH5Dq1erLMQH94dHvXgBhaSe0E2TJ4G3rI8xgAyUn9Vb8hL3fxhnojy8O0AWQ
WWJWQjGqZFjkrLwJ6YTZQvUYlX0mHjVWMhC2lUZgJQ0VInCL9QDhHxbG1T8NMUxKs1Ja4s6qeshFLHnKQa9B2s6eLm4ukhCRtWa0o3BQkAPogpgjL00JnzCn
hb3qGzm6uve8ThzFk42_Lw-F19NkxfpRGONjVX_L6Jj93tDg905GWo1SvMxJoExtuHz1pU1Ci0brw5HfEWVv0QvTyFsbhW9fmxQ9aY9GlDizuG5E-iDrBWtk
wATcYIaj7sy_U9jQuEh64nvWdKXBRZpXZloWcYjDOhmFS0LrzUNKOHFfKMwVv2Lu6k020AAquRDd_KjSMvwxaGybAx1k0wOOzNLk4jHPNgiQC2H4sgjlvTxU
cE2oIXBAMlqbRhhEjMaaL2V92fJqCQwgAQPbkt93_2ANxt9jIjuEtlHPhXsk0DnoaS7D7-Ugieny6U1wcPjVu2OQRuECJUrRt6gbFyOj-dxkBtDJVeJhak0d
EkIOW8psA3Urozn42jHphhU9ymetoSQb9TTU0rpzcBzLO0D7dk6cSwuhK9EpkMzPy6Tlzg4Z8GY40NWf3dtU_t4laFrZJj450IVjwdvMfc0Uk-7U5IPaT1Ee
D-J_39ySFNEt6rThL_96GKykCWu_SosR2_VKnPxSlOviSl-dHAQAgsqizIRKtRr8v9vwNRCTNVbDLq3lNSiUVLcNknrS-jQLWMMJwzWZuqH7_Iw67QWhkzoz
xpRNBjLTeTnUL_QwUBUOKxGzhd8H_N6VwzcVvYhSw4PEZ7b0l-igJtWolrsJ6FEF2IwM_HJjdMj3KGdg9BTSR_QcxXfVodQ3F3ZHnOhYwUHwHZghkwh93PSk
tcfFSB6mee7nCAQvfy5MTib4niAsq4LGo5hYk5_trIx2PHgjqYpNthg8YB_hT_M86vW6N6LEvx7S5PJhzcJVSr5NvgbQUVtUScN9S2RNiOGLiDEDpQu6kfLT
hlAjsbSwlzQL6GdulS8ov34gIlDTx9LZ72oAYx0nqtQ-InGnHgovQ9IcknYRNhhxzJOpNDILJWEjk_ZVb9YJfJ4NTMMgpBtbrVoPF6Twn9LbqEMLi6qkvi0s
e55wu2eJCbgABTVdOZGNgCkLPO1H2j2CFdBHZWVJxYegzGYfeZvrKTSmKwFBZFtGvou2spg_N9jLZnEzSTKl5v4u8MrTkIxMzwW-lj6DLVTxlRsfkMG3wdOr
sqKToVxecdtVOusBjpfwWbik0yPkQrm46eJ8H8uP6riBNGJPn0N4ncclgsjkkdUHjc96ZtahB7RhTNRT3TDTC-0AzRuhladhQFYbhfGVX93R7hpI5U9qxdgv
Aw0UQBt4nRnT0gt8Kgzn1SnhMeNvBjGVz3RJ5HlKXf1AJt45p0vQwq5NGEscH-RjyY6Aj_g9AoNK0LhhFbT8dFCutUf6Hi4-AKWtkNRxJ0_rooNzMHD2tRXA
B5Ane5HShULdUOYJAvQRUzg2g-LRAXQKm4QhDqtG8zVt3m
}

sprite $F_ [120x120/16z] {
x9RPqkmW28J71KI1Vl_7FN-eILLcJCpPzxvDbvysY7dyzlglzEl8wTUHqzzzwFHBIfr-HPEbNn1u7IPvRSbYrlBtX1OIxWOevKieALmvfPA_rwbPwxPKoWE0
bjEDAU2y0qlvTYWrAeT33S1xVOEAmTgHbNB-fhmpJpLDR82tadOB6NpKnwIlpZj9o-byDxwXeziKq7e1I5-HToQYnNwh6334e6svTivVSkfKXgGxJqLqMRgn
vTO_izIbyG1Syh861gCYW8-oi3K3Hidr5fqhCtr8550k5zqsO59YOHeUlNnXWxP0vaMN5NeNTuSh7JmRfazzLDXUVNKuPb_A9S_bebCrTRZK51PnQ3lVT-qM
lgVjolSspIejr1o0P07GbYLI02808Cj9Nvw3eD6Dk0E0qsrp233Vvrb5FfOYm3klg4q1DmV6z2pCLUu6uxAyW0D0Z7Hiw2kg0L3UyZO0uufC1ZYbkFmnpSwL
1u3uN8Wbq3gZst10PKyZZ2PlfvblKpmVW_EShm4mgO-yNv_kWMwlLPrp2ACTyqwbn_GucnZ7IcSoxCRWxfX0kp9juk5NTG-ZqNErxi0ucvOfimScH0eSZC5z
ZHNUMpV0HxkeE8VHfPQcCP6MpuT9ZP3su2TkY1KXurDc1qAkwjWajtV604oDLkRno2qEFIw7o47nuY_5iRzekHKtDE26lOydALxbSldkrnvDuZXWbrnz9ggd
zNt5-aNQIV3y3RGluHArsEruEtGtkE8eYpzSoM-_qjX_Up-Rgz33QmGJ_bIzlUut2W9H08-0N4VU_t7N7dDAN8q1bVnsvqll_HSo0oFQbnKJXHPN8qweEYWB
YjU2RVuPbmakxhbYyWiXC_WtBPQPQqTMURxlcdst93DxZobDEVbjGMNvw_kGIIFKYowPoTkTj7xzNXjH-IlXcZjEMK2lO74_S22Aki_cSQyxsh1KTIadloIO
7PUlJMd-H9qxrhjbstgMbi_u_1nUc7jTN8GjLHtB8Y9k_iHLLuvSRbk2FTB7KapTNLRr55V5rDtbgB5LCxNQN7lQHHu4liB-kouu57QxQwAzvcB0JUvW1Nsx
UBjsGukB6WxLxc32qhTRJ9Gxxs8PgtG7R2WEwsHPvMYqkVwbajAHgrnwzaKQxgfVRdT79jQXgqn2Zy1zNwtNWd3EpHzSatYTKTmIuOTEpUxqoOt2wwfzbpkE
s3hNyPttxg0SbbIETEioNE9rqdLtSEYsqFSSkyZFj6IPgtJ3VbufhDt9IrQF6ZVao2ppLIvYxV8AEymZJIqk9rpyWMltN1xly2IfqKNWnwDhSWVj10a2jC6D
S1b-GcrLkf9H41FGPdTTlmwZzZMkHnKwpFLbbtjTSiUkZVWkeDTTvlCot_Qjcu0YhsvrqKVYs6FhigMtOxpVBNk7jolNIpbmYbdlkBhAJM_TKjM1Bj2C3RIh
omjEh7yUCyzyw-soO112jBVBi7vYGtYRwojSvjKfr-ovyXLtbF1jLtkPNQo0ttDnoZIxpzFIP9jTEU6QnEDWFVwkWBQNQyfv9O-3uVBkmUGjZ0xkeDoColEs
4iRBWWGjleSxe0Ln2YfT1Y-KSdOtksZRCTbRby6hbPlSGGK-5N3aKiuIxd0rQcMx9witvyykySRH1LSxGPM4h6jTtaaGUzOTxD9Npk_wIfVdpzOBTjTsTy1y
YONNx9RBSTVWAcKYykCN2-rkEMckTfU-1vLwoMLV8-6pQqCvRZzqTOMBu6tB0zSwp8pTh1knqfLTroRGzethvDctwvjTp7Tft5Sk-aeSnSSEBWHkMyMriTmm
x-I20IqUBWgDVqXN5tIKvtcJP4vycslstEdO9O1WedtDnG8kRbE3lLqOP8_Tz0-vw0ZC5rs0VC1pq6Pbn7xkCAkhhnOvztC7zTY6qdrSoVhJezBAc5ukq8FG
FLoYnxBtjxhHgmgLytsNo_Ijfw-xxG_TiwhRNLDGgET2dtMLFcrorEtkzMU-cMMrhcIZj7xS5aOgtNGZoYpxx6hrw12AzBvhUlxhXDcu_L6EUkCQ1RLxQFFY
6jtTMrSrNCsHVe_soQZ7_nP_
}

sprite $D [120x120/16z] {
xPk7agDW3eJHdvFw_H_tZYwlPi4m68nziIjCKkbZPQMHTwRNzN-9oDUHXluN_gl_X-9jae_w_ZxQfUoE7YjMsjmeNpk0xcKVwWgWrGLt8pHvcLneWBQmJIq3
g46OPDxV0OqvclVKWP7NQ1SRq99C9k_aFMfeQqXM07ypN0EGdvytN8R673OY9ZuFe2SXj0nezZklk9DByVNxOQWAr10xjCLfNywV9EToq8B4Dwm2leEEhw8b
94K_gCHOLMi5HlarUKCT6C7BCLHYU2HkZpjeyLcrf_bJ9dXqksQFmdD1v5TgTF8dAP82FMoLgc94SqEx4JVDqCFFl0n-1-h-gMMyYq8h4MQJEyOwuK8Pj5kQ
FTc9Tsw3klaueIiqFu8WeKFRffrl2XJQqGpQtAO_luJkLveB7HX5fjWLBHpPkTWjlflwwQB-Q6hxCW35E2eQbmU0mrAO77jPWHuubAoOrPpyQkOgpLvnLwSf
yHbtROKfahoB7T3gzuSM9v98gD2UVtK7PFiKJCYjIJF-m5pX8_WDQ1fGJYJpNQDxXeOAG7kIPIHNEHW6W2RBgWGmLbKT5T2q7bjFxgG2JuOIoaonjYUngJtq
SrMtFy6Hr9IL-coN1qODV-VcR2ZFgrXe2WQIldNtDQUXPi_Nafrmtuxkc1kBv91rSNNWA2dDK6tbEhHR5yD6AgKsOmyNGrVfBHoO-J9JMvJZbLU0GPUo3msT
ksDNQFgbryK1EZEB0wwuhDnAfxscNVnVlJXlaWdLxEHrhYLuptuDBRenUrfownMU3ywOdU5IlcFHuqNovgnrrMQ1hV0sl2zmfyMoBdbWfEtGFoegFbPCMrOk
S5VBUcm7knJjj394XT2tk5HI0747kEw4bKvluKwYmC6kBB7Ho4tJhLo-Rbg2R4930TSDLRcP-sTiQP7jtiNlunFSdwfswos8SVWSryPM3yuweKsaZtBjbwCU
PYWQE-P9hZlFjNaFM7_y7fVVex__DAxtBt7rHgw4EE_j8yWtkPAujtjEdFWjRkeAj62JcvN_OIwd9RkEB2P9FiV5EQuKwwRascR2Pv5DhdkNkuxfmb4U06gu
dniRe3tkzqd9cENkv0O0TX7PvbgyH_7tS7bXG_QldAg1fZmFlSbzRE7TNhT3BYVEZ3OkpdFpdxtoTQvD7Axev8vJN9SQREi_nxKziZWvnMMmxBUSyrox862K
y3etDCNZzdwEAy3pnGGght0zLbUQwroxgLTtn8rSeFDE_2xkLuott-Toq0p6vKwkiWLW9B_1vQ3XmKdlvqvMrIkkL3jWx73bBQvTqhGbu_hIPoYRsmUvreYg
Tu2FCtHaklamruxi2ehNwMzmxSXk1unlSYsl_jEu8SgtkHAvjxFqliOLgK3b9i9MynskUwJZDFaOSrUW9_zfBk_1sdECVkREoWfWX8znxVgNY3DkZAaEy93-
4IvVpLv8NN29RhpNtC_DJ24oDhX4Tm18Tt8J02LqbqiLSEB8qTv-pBKpI8xnc1k1medZvJtkOw_iG7oH6sFAp39_dhjuYnGjnNY6oopZIXLES-tTg5xew1pN
iaoJdECAcu4IUeLBvSu7nyjSRYE3bNgTIt5lHvHZhWJCq4RecroArL3bW9l15O-wXniL7HnRUrnNc0lGU3ENyURY_inraT2MuWUuimh7Lbnouu1Dclkvwx55
Bj_Di4hz89VeFgDA0485RD9ycajqmqFAIlqEboeTq9OZzJMkVUy_ZYi-lCpDAxkht22FjdheZz-hq1kuYxTWn1zpCuVYUzpWdcQO2mTS5glcwzpT_sZdz_mb
Vayngr_aXXsenNkN6pl1MinVwZN_69NMTxYCxu5SqprkRDQa7lu6lnoz3mMrmTNkfzVaThZy1DH8v2QOzhXUfjSbBgoupvqPo2cE1JH1BqCDxSEQIwM17Orb
NWMxs9z7Rt2vtcwfBV8v47fPpeSdBgU_hgXQ8hbMgM_B1tAV13IZO_pKRuhJJHBVTtidrRFrZI3JdV8-R74LW1ernZ3TBmbFt0wCl1eqdv3pIsx9bolrUbK3
5jr0wAVbbrn2loFnvDeW_w9SK0t-V-iFhQxh7m
}

sprite $D_ [120x120/16z] {
x9Q7tcif2CG_i2lyt_zjjtb_rxWvfcqlf2SZetDWmjVByN-8_XMayqNbpsPTR-LFufJ3Dt_6GVzSQdaemv-Wxvz6dRfxJm_pXcPO-ZrxA-GQ9G_7QpnGQpQy
fv_1lrThbVujaoG7waNQQ61B3Os_cJJdJRbG34RHZRGvLi9-VFqDfvPGBWuNcaEFUgjlk5pzMPbfpIg7_JJmyHDPCkZXtDD1toLDwM7nIkgEEIC_pYog-eQ-
W_G4BbfnnulAOrXnUwtAGb9DXe_qG8xcZAYQ1bYH8sirQ44aX6VwXYYJlHhUBhKEPQoI3dL0lyA5FFX-7IGykjHXSuNGWQPxIaa6JRQlsZrEee7ltH3ZDQdU
rRt63bRNJlDmRsjpYwM1DRqnLRZ0gORxkZi8NtvHAypathDSuoHFtCymXt72wMrNFwd92bW7JuzBF3iuG7cCcqB4PNkdq05W3sYNJKD_cgwE_FLLWPxEsDai
hHXu2G-AiZZUKnvEZq_IKQSym0Zd8ynYbGBuGSFYO5D0INvC5xuf9-jV1glnrsROV6_YM0tkQajoXx6qc0cjhNHhzGIk2Dq1pogR-LjUa0Ma1LbLqi6RtkDs
5zNiN08bT9YsDutmDBH8M4nh5oVSz8viS0lS5sZk3lHgIuuLEn16Nge_mlNI7FRfxDvwviviaPwYieQU1w5srODo9G-0Z_XulXpkfKqNFOUK0K1uPH0NYCqu
3uyIctjBontrqAaTi1f0NkJzULK7FCkbRTgD60Mm-nrg_-vTR_3E_JRmtU6rsjtv95R7Uzf7-EM2R_7Es8TrJUDqFLDVk92dFSn57_5ErvjT6ErX-KgQZfeS
O95-nhic5gV5C-kosrMFd_EkKD_ivZnMmu_jseUwh2eC1M1fGH3o_ezxhuilK_BPbTFNwVNVeq92PkC-F-MQoh4orxGgMsnraQjvs4KzMTu_qNssUjR1bJgW
weMnL5ZEI9rSkOkogcK_ptYIkhgmSki7JCWiFUOvrvvr9Q4mKaaPFLt41MR2JUtgreNVOpDSTsCcqztLPv1n68ZbBDFVbJCNkc53iXFrTwMgcrS5nPZcdCid
NTdLpEVw3TDCUxlisjkk3TZLlDutv4yctyDjhyg_x-N2_buVTWtpwougLv-SAfbdNCnzTFtKhXZCqX_TTIrEOiVg0ku7vOf-y8vhQM9SN-RXe8i7l7wStIsV
TLrvdMDEkTBFbUJWbZDko5NwkmkktA12xeHhNLJ7F-KUx9yn5gk7NQG0lUNAl857l-jYu20pyBkkr03cGjQikyOdTUPynAqkWJPBhin7HbkhUTYTBoD6_6Iq
YyQw3Nuwk4XhMvqHLmOrClXPTirjzrNG75n3HMvyR_TLm2DpLkEslguCkzLuiR-B6CyiXQE_gzVlx-UEDVaVwxfKvhwzge5sNzTHQNsx2zHQgkwk72Cp1JUx
_sUSy6lJpvMoDesp1xSboyYcYsiStfK1Agu4rRCczxnhH_Gz14QxxNfZt6QVT2qwa1p5qAxGLIhE4wvnQ6P98N1rcEK8zOgzvlfSUKu8nrmA2HN7Nt2_niDS
fp4ST_53bi7g5TT4J7jmKy-uICpje77MjTWE2fxVyouoji6vE-xQ03G7vAeh3pWVTNbE2iWD5y4RJoNvFTV5YRbYfJxW8kqrarjts_Nb6f3dt7QzQrnoPLwP
gOCR0gKYPKlSTw6fg3JFkwfiYOjvj5IQBgukMxFhKfMLsjsLibNmbKi6sjkLnDBwzY3fxag8EGQalwj_xuPhBxjwF-LusFMj9tZ2pSprcEi_Fil1-ssNcJR_
FshxrRxhlMw_TbokKrpz_p8ZjEUwvJSq_OPR67REAUSybLhaxqcbvBfpVvrLeA9vSSs4ob-HleaIjvIjvzbxZUeOl-BI5vpR_vVh--FOS87k9lWbznlEAJ7B
RqY7lEZw2FLOdDUkLF-bbDMwuBqPpiKuxSfpgvEWBhb0pySwhrnK-7TgbNFFWklTS3tMVxZ8n4XIpxro2UYT6EkRAubDfWtNcU696FTj4Dw5MdNTy5mCbkSd
pRJaPZiy7QlALjGkdRo-LrUrSltGCtRHfRwer0xbUjjVbJP1NAyUtzunVdONNcb_cU9HzL_-0m
}

sprite $B [120x120/16z] {
x9LP5kCg34Gj0nAJjF_blgVAyGbjREAUyjNwoQHmJQ4gjeVrh_QmVnzA8QR_Az1NgO2-AeQlwHkTEbJSlw5lkgf0tz5thXZfhyrlMbSCzEUXnHgliLpD2lrH
Q9OGgvaskQLMDNlzlFyXQ18cl95cfkKAdPjPB-yf-trqg3nEiwYPvfE-pSpAwRlVSdMKoI0K7Ds11i3rhN8vPRyQ3n9l7kTWCVJDjuCMYMZteiVKL5QceE3Q
TcY-B6z3TTaVG6jBdtfOVRdAwGaOfPMNIHWJDxMsy0CEkVCctMM-HtDHKxMXyjsYARuyuzkvsJH9DsKiyEhhSkTe_2GsLgLvmJqCCnXpDorfR0EeMiznb2Uh
QPNpJbsAmicB-mXMEUixQH2QkZJqrhUQrjaVqVi0UPKugALt3M3LnkE94LsR2KwXmpurxZUXXYn3TW4gTtCzdXsOTuLuR9oxjQKNGlO-7EgmzMd7XUD-_07S
5Hep-V6Me-1zUZtVUe0bfOfD-mIiCi9TfHawXjL-I_SOgQQN2UQ3BzN1hWYiWzYxjkkUYXi-7Nft2TTGxfuBTFJDYUqB9JQ0cnokzOyjJDJwuzUKXyaOoaLK
V3tqrUc8UpTKI_7zlCrSo3YOe_H3XicjWwk9gqA6kQ-FAIhkDUiOR8cdyt5N1thVTdHp7Q4Do-COBhMdrFH8KIwOE7yEqECfhue1xL2LdPRNaGfvUrkCEILS
MMMyGd34F7S2RIr-iXR23p6zh50DqFo3eTfbx0CypVUKOzhq0vXsnbPp6ieVHEcgsunTdpQSmfp79T164TQwQvEEyJVZD1Oow9hh8OQxDLn0Sny6-kNMUTV4
lYyie2Uk_r3lk70lR4ddG-XyqjpdfWQQ1XHpFdDnZWlkOPEMXWk_yop1OQTu658TYicSk9FG4tU81SsHzbGXstsAc_S576eJG6-u2YTDjPzLIDsywYVFYBqA
WxRWDX_nJrnKG4BmsjFOClJzm9N7t8sj-Q9bN7G-OciLcrrpSS3rALSsOdKqrBwwk5HeIq-vxJ4NcvBPrOVL8GN_OQvWlSCbGuhkt8SRwI6tQ-UdN3wb0gv_
A8_8UCv5qVQOUxgsr1I1DmpvSsxSVeqBH3V5br_bWb4MS_1Vk_Q1t5W8107KJKR0tF-s6nglfhH8zHFyIgQYurD0CDEmqardtLu_HsowQQORIgKhKZ39JPik
0n6wBDorOFtW-XbkI2naj8zjt6yMkx4NoY_pokeAkCQDfMcdw8Pug0PZfSrsMRUtGdHmzNbB_b_9uaRtZP4blgllIWhRdr_xdRpWiWlM2x9ptO28wJaaBhci
CoNR9dwlotQmiJ0-vhBUqFUBkyOnbsr1xvJesZTk-E32LmsC3hjiznyiZ8-up2MaiIC-wpxZXRhRhKtxz_EknWR5Rhj8ebtrHPS3MRGH-U0Y5j5wSuhB_IrL
lck3gnD1QkGSd-hwVozZ75tBPvhmjLq_7tUVCGtpGhh-cViqRcr_tN31RHzS3b-QC1yDufdxQATwpJLR-n7ZXLQoF1WAiM9Oxt9OJbxjMUvnEV3GZlXEb_Fg
YcjngwlrSmkurKsjzhrLACzn_OQRM4VfofeTrhiCt6lsxYMAoLZhCen8NkUphe39B793hdfehQwkWCMxwMwCHG_f1_TP64rt6Nvjh1lQiCnmUSee9UtS1oiR
5fnntH1x7wZROHDx9LnmyHrxcxBVxP4DZxDmoZMzBUBRLO-u6iG-30wwwB4XApowntCLopWksxpVPJihZ0tFkdfk9X9skK4QpnCn9KTYlTZyM7Ez-xtgfkPN
_PmDdrocC_gwp7A3H9uVSjiQNTZKWmH-RwxRhnNejgKk_gBzn6U5g-U7BDnfz7vHpwFdkMF-5sfFlgDuuukydB-dLIw7wVsyDD7OUxshsvO68ElTCN--turl
tB3VnP2RZVzlhclrdimjxlWgOuwRDrrBwKN6CdVZvZ0ekrMkek_eDQxRlileskZcI-xEwz5mfzt7w28IFJAkkw1vimkOanmEk_gzwvUHZxlWLToRNM3Q5Nli
T_FSo_NUxt6H0jMLOtIDMswEBcVItIwCkG74gwj1upqsNG3tgVfypTVz0mS-Cp_ZDm
}

sprite $B_ [120x120/16z] {
x9O73lKu28IV2zWOcFiVTnKHPLCSl-tr7_MqpvI1V7wXVYYL_3T0QoMYIkalXUPAX_uoSgQRyby1hPKUgZN_oPrKwKtbJyjteIygVmAKr4refQuEgUaFZPHx
fU60DfghYSEtkqpvZq9tYK-bgW2K9w42CFuZhPMOppR9h80FlkONi7uxpU_ATogjFTvFtSuSbZZ7Gxyvtrbu_chA7O1t8X87cDx4-PDKwg-2hgkKDg8he9sM
CW3GNdvXVbLp-lQC0S1WMecnoxwJ2-SYWFK5kGm700VWx-IcZaD6o_oM6fxX0IZdARGP01_q-LI99fj1XyErzs7ODLvZhlMSoUQ0bdGtLaJAnoaGvhrAelD2
Wbrj6aPEZnfsZxYEesXGogK55OXX5U9XW0jVChw7_FH6VcdSuV2-9J_J002R62DtmuxYRd68cxfZK-GlVKBhvgqEeEl-tbj_2m2u0_16Cmr4WJWLtTvWeQ_B
o2DBb3zBJoEeBsfXPXBtBKu3lBrlxQYVTVLltD9KQ7ZqzrI6NRHzTp_cIwW6eASKwsYHv-wnjb8rm5w2TeJydA713y_iJNLUHzQVwDo6K3fD7eK_9wWO3Xs9
OmjhfmDQ172boJgoIxvJ7VPOMraS67ntalMTpUVT6cEe78DGQvwl8yVFvodMSfe-9e2FSBGw01SHzU3sgsEw0R3U3T2Mb-l8UzrU61BGL_ERY04mOM83TkdB
n1_njI-kTlzcmTG3mxU6nkJH6fLOabCpM7EubDLg4mU0VXaUeJJv9i2w6XEPnjxMD1mjo2zh2mRmnC9vojqQt06CFDkzbp9Km3azI-j0VC314mkNEJVcZ-5k
rofs_palR81Ud1JzY_3qZSjhRgY80KhvoDmDS7viBqkgWatnu9DB_JitRBYl8VP8wDilMMovWCQ3SoxvItqpy5mqxjxgPwNC0vlsoVhEvGNtBW5Wb9VSw5MD
qosuf03IB-CoH9S_XHiKsY6Vq8hBk15Mt1Q9TA69QM8Bv0-XhxaXXVuAxZwcW9xFw2B0J-tQXxAb80m6u0bYw7d_jzqIzrzlOOuWo5Qdd_RTaGiaFsBxvZRN
YMzq7MfGCgopsk330ULAXxiNRdRv_RQbHVtcaeYtUBtPjTRqklXCr3O5JK2lMr4RN9GPal5tBtA1X4yVM-Fwcwwk0Z7OQzTFT7rAwc8YJ73zfUlYKLrXnoby
uUupt7ZKwVOi_3GUekTSrErQpiF52YXXeuTSbz29myL5ncbnJKRAP5VhddAsQxQwiUIA6wgk-_IngliTZUvY_dBHpPi-_g2zvT8M1UtXInT9IObstBNQVBIk
LoHYN4ATrEN6qoNxemmkiZUxw6p44TojooN-kLdrkVeN-u8wkEvotQMppUbrSMdA7grfTu-wFJj5xxh8AqHQtQC1rD4PSv6o9sSkNBBXhDg7NIn4elUxvY95
Edenl337TS9xrlIZwfAYoRAusUx-lH_K1Cs-Sz4OwJZiLPS7NUH3vJXuO7sDekucnmZimYDkgRi8XtMUgAinpB5xZhlN--3H3qM96Qtk4XVz7ygZLIx2Ra7s
iTJLyHrmwHUvEOTjfSknvE-lQqd5PfAxlt9nx16G0I6wUDXr-SX8xRiT1z75GwvB1UUOSCyLq6_qYClwww4sZpJPLtgwUw1SdxyuoK0wFCcb8YZRg-xxWyTW
QDn5hvcvjTzF8fZLdQxz7BVtxB_6w-dJTiz5QAozRUfnST9OTkftCLX5ty-TBWBWnDJd4gU2GsAutNaEQhPML_1FEPuZeM7nMxtsmKLOz2RcLon5SD9GTOsD
WjiorVM6YsuVDTUce_tpyrs785Rl95oCWiRUU6cwY_F3eict8cJA6NlFTnrSj5_PavETz0PmPNcPxfxRHn4TSFp80XUv3yxxLxbuBPXAVFguotZjdalKuFgf
BWRZFRqzwre33V82rsw0tj6ZRgYxbm-oAcsVSLy_7KwFkDOsF55OSyEGs_XqDErttVZP9QWTrxWBSvcB2RBATK07LRhbccq8XTtbua7CAR9lTh4yp99jWqiU
w2DNtJK6ztUXImHqfOk7QvUwHBICfDC5kivcSGHrAUpQX_N_zHK
}

sprite $U [120x120/16z] {
xTa9jiCc30NG3vWPlVqljyqxFpgEO-FP7TKn2VKr64aa_TaS_uTrzddK3FxF6Anv57LKAG_sATJ-eagx1oPDz3lipGzrHjLPt_XG--7S3JDjoA7FXWR4IzKX
nvW5aBACLe7mpWPp3Uf2ZhnqB0BK56RGt20rlLzvUvuEBKwM4cqYnmP8dDo9FOMc6APJInMG6XNLzPt6S8msBYvjfDm0MY4Bxs4fdDcjfknxaG68SCsx4TmE
rCPQ_5eKlEZiLoBbOVFwSkEMw9SZ5aYBeGfGOtSOIeY3sJ3LTpe2Ki92gW9jD0vrSHX-Bn5y5nt2I4eLQ7bAnzBuRdUSvhhN28kRp7qlM1REJ2CauIgiZ0jf
jhQ5OBxHfVsO0RIaLoUwD8uqXt7SQiEqhhiZgq1Aggo4dOWSLw7hkvBKCVgrI03G_6fa05XDmL1UIUrPzhh316ZyM-xUN1D8NgbWx5l8hnvN180if6j83TnA
NCVb9Oo5NgTYwzKWrND7CTC0vEyfS8jCsb4DixMhnSznydM7KV3RpHnT2gGr3VMj4kVQKGcVlHSjXPbnBN_kJktUTCTT1gYHdyIg-VCL2eqUmrnahQAn07eR
waxM5Osef9MDss9ipDJ-k1gBw5ESSnayHgrTRJI5j2a5kMixBYF81fWLa-lO7yQxuvYkowYe5Tt3OnReUGDjaUO2Hy1lTGjtyqAsfifr6oUklfniSoR8PhUX
w2v33KkzL-DhU_4jVM-tgmqjZ2fcZQ5JrRH1QEOVSDLYjeRCXj-luZd48lg0JhYC2cneD3eEH8-u-IjReUlO2UO-b-GgrmkgGDlCOgjfWk2lTRcNbyfdRByV
jKtkiCFbf6QpEbNHLYOdN5bo6RbzjCUGDTNkTRMWQ2Ka-e2hpPx5Wel-X3kjc0-xkdSlTDC3hc_XOJVKhEVsnroUsnD_vapjimBYDZTaKlmUphyAoznPj-Qk
6vdsxct-lCBwmWfumWq2H2ovBAOrM6hgyaLY1OmBRWXzDu8nwxAOjaJqo-MZ1cFMvVPRT1jU8RCksx8bDECoZC-OwxC2Ve1MIqufvrogZ3PC0QFwBpTm9tag
7PURZ42Sk7fn3O4UplKWD74ZZpuakYuZ8GvrGjEe64Te82e0GuAdEq4TyBFL3VpD3ZoGgpk1MnHmiQ6J7RiyLtA1zxdSuDmGwl8vBaJLJHJqXDSyBxEmpj-H
wV9pbtY4eSk8SwWaOc-N9vB6NqGFkGp3Uw-0dk0cPkEpK1T4Cz4JBcDeu-_D6Gn9WZ1xSg-i3_lTegw65SxY8s-AO2JgpWvKZxd-wps1BmBzLaO2c1xRQsWW
UyYjiox_7n8tZ4vQNMvyUVtiMQztN-72AAi5esDx6ZYWoWqkm-WnGV0xRIb4xtNPjeW9MAugZmyFk9hLBpJIkSHjgox30uaNkCuTjhX6UC6fQpQwnZplMYvN
jcPYtEgQ8FpTczdddd29LW7hiFlnHO-OzxfcoFoEpjTMEquRteQxmpKyCVhnCzOAcFrDhatykimBZrtIMG293bUxpbSz2qnTXh45mEMk7jkNN6wueWVj2rpk
dCAhzLp62mQoCsTTOwD0m66Rt68zcvqzuvhOUDYIhMv5Vksor80QtJ7NiZ7pFz_bCbpXwTliTOsh08JTQjOr7PTXXm983MQ7EnHveReziDjbc5Zn2hFDXMWw
d78PYIbeLbsMsyfoUy1jTAS6-4j1nsLxWN0ZNkHoSt2zgxTphXcIS2E8cCEkpBgiPSAsDNLjndlZdtFJhCjvnSPzeoxp7AY1wxl3DJjSXkDpZExbigvfORlH
PHZ75iu_jP3VxshRqaozniMwowW8_EVphZdZpWoCjxfAcaTTQsTkuRnhkwwPMNDpjskcghv_siMYg-kxGD_ZwiYEB9Uxwoh33HUw9cvJ6PUvdEhJhg7wZ0jr
hJqbcYEkiMUdIdcVQynm4bNPR7UzkmXbkBJ9jINyt15zr_5izx1hBLyzwnfhx_VUMdkxYZvZqpLQb1wJ6oo_RJmTG_pvnyKV
}

sprite $U_ [120x120/16z] {
xTY9bkEe4WHG0I9PC_x_SryvJZjFMmMI5rblcvXzJ7DRQI1HBVzrSU7VWgunhj5VZjuJBgFz7JNw0jIjL3TPlqix7wTPlVkI6k91rY_8iVPwmAQcNVofJoer
DmLwbXagHQ4jnHXFgtTgrA9q03sDrAn_VtB2Gpl9cIeZkG5QDtHkYbvaiye-GKEowIob0rhaiRuoA7nmxwc-vDbNYHjzho_HOMHz7PMKuZofti06j49rBeUN
pgHMub4om6SzYBJadbD3aWfebTtP53sbsxWzMge2juaEQRyAvyaDNAEZIEdyR7ySXw5b_hl4i4UlAJ9CKK3JSAlMU3Wkwttj7UtgTNm6zRpPH3KDnxMytMk3
XUb_rtTwvfgK6sUVZjEQx6oPZNkiDz5PKWTGfR6QEn6EQm0qxyuNQBgKua6a0bGF8erxwt1SAZzq10iqZ-GEQDVRZB8t6tTLKvwYUzCfK9ObD3xChBbcPPNl
zUwpAQjr97uZUMywzCXRH2Ozs8QPgohljoFkLElDDgxbE9mEBKiCTEttqTAcRk0k-hLRIToHr4VbAhgPJYgidTnTgxjrRvbVBwJmeuV5FcjRTefMJiwAcllO
PQ0rLvsUVZPGQ-9urdD_NEcmxsVWsbOuRZHyqAEToYI5bN7ksaYjSJ-bGtcJEzZvPFbz7RcneNViNXvpOzdiTDpP-EW5YConMxd0PxkrsGUsi6PV13zvrkse
jcwroRPmt83Rn-fLVkzKLk95rnImtYRq4hVPZajLRUU_vTe2vshakHgdQNzQHx5r_e7BvCg-m0Mq5vwYi8x_Xbj-JGax7UUHr6tdd-H6nL539weAiYUwx3Ap
Ov5BgPSK-tFk-hnhNUPN6v02st3wWQjpbstB4ARQR-MhBelQsQxOyEtk-7NNThNQU_XbBf_QZgZhNARJEDFD5xYnfPFSrEfpRcgPztOjyh7B_NNqlDPUVrpd
2nvV6J5qfSd4jMjmENOvi0MtBBS_O-K9kEi2g5ktv5ngRGgcnmENju4cdgXRRd5s4PwvJ947zo7ANpjrfRAnU7BctkgT5D0gKvTfCdDbp-LfcWEnksjnFFVx
sCrtMbl9GXUYiEGuTpilnfG6BZFv8QGYSX5OUkVjmbBYn1LEA0QCN2RmYp3QN7v5av0Tk8bh3c5XvYwJaTFsXLDXhmcZv3XmKr7M5rYUT6LPNEPZR5q-0p1O
oLktyDjOV-PxmULdQ-RbvT5bH59Aef3skAtfMbcw1Cu7kAVSGfVX-cz9w0xEiEqQfCk2z49qwZ9Zbt61is3eTgWCzWnGFMT-ssKyordajxjjPLA9yiTohxlL
N8jJiDuRT_3QYSmvttFZierYjGDbwF8uK-dmoxdkiWJRrLkNZQRdTLdQ1suRknoVbTS4SwtHjC01JSzt6HSoQRfsRL-fVTErjjMoedGkDr9VTvcrWr4kttFS
VkGoFgeryhFSzSXbbFFzfxZkIJVs7AvrdTJyuohGnJ_CzqNNhGNGj2p1hUmuyGhNy-B86vw_TnmjyJvV-8hBSxObJawNpryKGFBkQTUzvFgLZqRDNCQ5mexZ
SBwxDWNAmsxtZoiDjwmdkmgjmWz6BkEI0YZUdUBoxSUkxLENSGsyb_aFNNlR0yVjkan53Ra3JS8dhl_pTXlqIRUXtgPbEu_lke5LAxV_UjujzpuBQ1FtihjM
1JIlRhRFtTnb7E_WPNKlk27fusidNdT9WtdIXVq0Wtd5xNGjV57Y0Zbo-SMWiSbyxZ8A02twYMiNFh3ld-bwKRQjiUkBybDLTx9xMwQvissvZSj60tQQJroT
k2HuNyxUcUjZXtMQ5rmtCFBKjRQLFLrf2kiqttEjRIdGWAgmJlDzbn45x20znyMnotfti75SwJADy_rNkNwXxYvrFJt6_Kq3wGFNxxlERGOuTu7htJA8-zp5
r6LDPt7kEoxBUn1tlilo7iR9UgRhYartcFDSVdDNkwplDIwyFQZxH7NlkSuwneNFwp-jhpspUzuDFYpdnPNdt2xBsJbsMT-BNUS2wtkn6zm5u1-ZmsrswYKo
NJQQA-FSpUM3NXmdvNdrd_mB
}

