@startuml

!include ./sprites.iuml


component "<$AzureCosmosDb>\nAzureCosmosDb" as cosmosDB
component "<$Azure>\nAzure" as azure
component "<$AzureSynapseAnalytics>\nAzureSynapseAnalytics" as AzureSynapseAnalytics
component "<$okta>\nOkta" as okta
component "<$docpath>\nDocPath" as docpath
component "<$mailteck>\nMailteck" as mailteck
component "<$generali>\nGenerali" as generali
component "<$generali-vertical>\nGenerali Vertical" as generaliVertical
component "<$cercalia>\nCercalia" as cercalia
component "<$nexusgeographics>\nNexus Geographics" as nexusGeographics
component "<$ibm>\nibm" as ibm
component "<$puzzle>\npuzzle" as puzzle
component "<$ibmwebsphere>\ibmwebsphere" as ibmwebsphere


@enduml