@startuml

!include ./sprites.iuml


component "<$AzureCosmosDb>\nAzureCosmosDb" as cosmosDB
component "<$Azure>\nAzure" as azure
component "<$AzureSynapseAnalytics>\nAzureSynapseAnalytics" as AzureSynapseAnalytics


@enduml