@startuml sprites
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!include DEVICONS2/spring.puml
!include DEVICONS2/angularjs.puml
!include DEVICONS2/postgresql_wordmark.puml
!include DEVICONS2/java_wordmark.puml
!include DEVICONS2/java.puml
!include DEVICONS2/mysql.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist/AWSCommon.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Database/DynamoDBTable.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/Database/RDS.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/ApplicationIntegration/SimpleNotificationServiceTopic.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist/SecurityIdentityCompliance/KeyManagementService.puml

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/apigee.puml


sprite $generali [381x64/16z] {
xTk9SgiwkaVnlqO6uwptVzjReQIA7Jv0EDZxTZVhZ9OL4By371VRM_-cgwkhgwkhgwkhgvYxvFNJLUxqcQZfl7m7aFHJrdzG0VYKlHH-z3tjoMmoffH_SGrR
tDW31zlvaR1XWlPtlVD-eptGFImsnHHJJdFvkpI_2Wb8ENuFnnXM5W_mH2qfrX4TvUhVYG-iu_CH_38H1FAWrQR7DpjeM3V0ubWMg-iM2tQKLbViVyrKBImF
tyFQ6gAMXLKxIZkQIKq1V16aoAYEHr4lzvFt7Y38VxzmVh1NC2oMve5L_ELOot5cOBH-Sk7VCgTR8_Ilupkrr9Cr5-ircbilyM7NljI6hzWmgsJEqrCh-9Q-
MoDyDpuy_GkWcdDoSv8S9DMNhi2tNgwEDjRSZD_juyl4RvFCdy47u04_WgmcfgUrRUxQi6fZDMVP6xpluciVts7VNoXrRyNFeFnuoZlGilIukKYxVQqHNzOi
-zISpi0NsyEy5P-waNeBxsYuuzzb5zVNzKTyT-osKteLl_yKVlVyNm5K2aFkSfSZa7FVTLtkvnTnxqDh-0D-NC6duRPp7Zu_lHD_f1FGQLpWry1uOPQtbjM6
hpLyZDlE2VZJ6dx_0Nm0RY1L_6anONny4RGUv-ChOnvDRZhp_Iw-QTn3gFF3-_2BoOJ4l9kHEcudlOeVjl71nXUr8sT-FVPT_Bir35Z8v-ChzJtSDUAULZin
VTs0aRdfpjSOrMBVoQuDF_x6j_KpzrFmMSMF7y0l6qgmV7OZnmiFflsVyBN0JvHyCtuwYXz_NGtHFfVEnyzE7L2zuMb3NtquYA-L-XVnHQqPdwFulyTivTFn
o-H-eO1Hhutyvgfs3W5OlrYejUFxjbCZCZTO-E6T-9duSAOly6_KHRau0EpP3c_33vHY6pwD-FOWa6pcq_0T05bW7B0P34f0r-3PYZ_LbvluejQ4xvgVK_Oh
kdehVWOc-P-poRXYRGe7d8VVbrSx-ABMWEzeFVEZkU3d3G7XP7o8qRZQ0VBUWo3WDFnoSzt55wMuYm-j-ApPHsEHv-4dwdlFim2lzHBpsz2TX5zgmBzJil4N
kTKzthwxtsXu9F4UVCryeVpRGpr-zmEDyz2CRxCSnnUr5dpxp6_QfsEvq-5a_9f7Jt7JPZtCdOP_Ry0tVdsZEmSVZ6dHEAJJy3rpaxyl5ZeIj9VhxMrl8iwb
nSXDtzrQy3EblKVAqFPf9vdh1PRFFDrf-CQtBifXze2QWbVm_Tf7pTY0Bsex-DeyytU67EO-JyHV37I0-Jd69KXQDk5EmQ-2BVYYrC_uN-kApP_pJThqLlon
FhY7fwiUzDIuUGSz1V-cKWj-fBJtI7dw4xxrBOPmufaV0100KH04oY1PNnS3QC3FxyONDId31c8RllrLDtkN9-83iPvC2AIVcm2rSNw_BxC8AgrY_GNVWG4E
CYb6TMtu8yUUxG3qZBVlfky_M_57cl4NF-Y16rHeyEP3tHpUXQycV4T9eGsVu_Xsmmu-H_0117n9cdXwmvWTY0hKoYxyM_2zXM_XV6tiERo8du1-68VX-w-n
7yQUsddu0DI9OWj_8ZoEncxz_mE9kVGdV0nyMty3NuINy5dVeJi9VrBAFs9PztNyEf08pmDaM3C-YbzgmbSRldGMVgPqucr73bIcJ9luUHxWhbhFZ2y0FewV
Z-1tn_2pPTQ4tnt0Jm08W2Jsp_n8zmk_4p0ypmuVmDSHV8xXixM_l8NF0NmWL2xAZQLGB9VNFuuwW2ZHI_1xUZ7-0_wmYw_pyQiKE_ix1TyOe6xFtClps229
GV8G83QS-ktuxEF7Plnm33z3U0q_7CRtsJ_YMrzR_ct_nV3uZC8jLl5NVDU0hsPyZk43CXefhUFJZj-NonkO3MyeeRcVV-c8Ae7xXH7gEU9pSjhLRyUd1L-D
-E4SVEtYXmFuL8f0IP7VXmvB-p88a6JdhJrthVYquVisV8xXiuVlr_0vY5_VSnMVGkINjv_XKJ4k3i62Nfw1DlvWNU3xlmky2Py6VDU27oYju7C4_-pqL6_9
ADZuexMmnGc-R1y_qOAl7odA2eqsyJF_5D_SGV_usQIC-dLero-snzPXb6cl_YRevMbBQKjiNAmy0JP-zu_mHMcuFque-4tRszr5Xa9wV6F09iThMERSp-AN
1kljF-1x_UuqVCLtuf_TrTNLrTNLrTNLrTNLrVy1
}


sprite $snowflake [281x64/16z] {
xPpfbhki3u0DgBWaUUx_QlyBHnjBgvrtpZkd7zhyLWQAuG6oeBPxAbcTDUqbcJ26hljA1ZVOoQoO6sFtbGLpLqfNPK1nD-JZkIJCtHsLMfnhqUYxAbympX7C
ryfymNp1_4nIIZy38xNXfuWim9HUWv4HyFmnO5RC3CPNO7fmCtZ_eX4HgV_9BtN9lzTsGDtTZBM_0fCL_tz1cT-CfP-16a5CBsUfX-7NO3OM1ekSWEbb1jsQ
lHdC26RAr7M2lWhA2xzNTqIzYYdCxezWdCKmsrgnl9NBW2f0xZenexoaEFq-ErBRS9Zn58o3-IRwvin9tHXJDHtYVmGcFgo-YJq7OxVwT--aZ4RmyCTWkdub
XluKJ61vTwoNCUJFm4XAJmpQIp1MmvttoeZRdu4fwpGtSPfCO7O9nc1vVmXJSFyhC4L5kampoBo2deCnG_lk_L8mw_u8ZALfNLF_q6Mls9dnDHZbTSQL98gI
Rpz--abfAzBbvj-wcd3FAGMOioxpSp1ZVwgnp9sEQv-MhXlczMWqv6PgM7RWngDnaR8ihGtEPG7GmBVyNwLKLa2NbgeCimCiuzwlh1UpdwlHxm7S7L09CD4b
0FCejRVv2HXPO2UJnWM0PP2zibkDb9Uk0FSh8SsWPZUFc50rTJHt8GC0wzrGPq1joxcgz2Zz2AYfSTCdkZ0rLQ247pvTCnE-Tfsvrf1BTIMtOCQjImF6sfi4
c82_CjwCAhgrtqPB7bEVfp6ZPgq7pakbVW-XRtsxcTxDxu8gLKnPP0DZjLX5ZUc8qTHl5LhR9yuFtHFrSaEi69e0JnPCkNKv3xWzW153eT9FeD7-fd8MASXc
GCnPxqO-38TY7eQXMLBciTiYgs3gHT9Wh9GDZ9j26L8UgzfJS557Xonfc44nsTAQvJmD85Tb-WNteH_atiR8Yi8oPCd30Wf62wRb0jF_suzhgD2lypf9jt0L
d-HISfJ22Aazf4o26qFuVTt0OAnf7nfAVyCOgpGhohplfUQAGPBbqYlDADxlCskOUu0vSb6vSLdothwMcdc8zB4nZptGwjaJRijOcfKUUwrgs6D66ABC_ecC
EZceAihmw6E6cAfC96Yb3V1k8udsoR4Zc9PBDzsJa3NoZ9rR1FkD9S5KxOvCFYOEvlHj_j9IL4UYFEuBOcbMXk2ED6Fk9gBHY94km8ZL1Y6f0TDmIJkNKC7G
u-UReIxfmCNDx40cJM0dELF2c9-0OMmkNjhb5Vvhgyd1EdHVw-XEm3IN2fG1fk5I5umyg30qRjDYk50EN6eL-J6PCeKI7MypjhJxhdM_4vNU-EYM5sVU0CpX
jumSaFehC1EsZpdsPtYbbeiq_g-vTDZAutxIu586VDTkHkqYbHnH0ojPBi0CL1tNy6VnSJFPJ8NikeV5cMhr6PZdvrK5ku49BW6wv3xt8NcEReyEs7Uf2ofX
NiEEWMqtvO3dzyuzr5K5jAG0usip_3ef2mmdHmc2CTnGcTCuvRCLeqQhKdy48yRH3uoOqueP0IOyfczIUMJsAHWnfTJB19UXUoAzWwiwBFrJC35vZwD8R5hD
i6uhsq3fmurVW8a68Jd05B4zZ0mmRdVYuAI_0DD9FpcW2hFy5io0adPREECQGSolmVYoeg3CHp2chTZSRgMftKg2sy-tKiWMHIeklzjATQJZjdBsS3U5mxZO
IlbqAnaewqf4tc7-Zo9DSRptmhPDjhqolYUIPrmPJy1inZViVsWg-x1NsG8wSMEALNHjVCTJuskkc2HSwQ_JrIjtFSd6cvVk-hnBGozMpCY3cLjgJTYJYTga
r7-Ms4aNxjfEtRKPAfjzw0yHLIDzlWhm8fmpjvS1tebCAEaSJ7uQu0t1g0Z6j0VK2QM_0XCTDDdE1cRtqoFR7kysyAroVM2zI0aIfke_IWbQ6Q_1L8-JxsSt
z1pnTTeRh50ByWACcBSfmIs9ZDYltCZqQBETCoibDFstaiWkfViWShtOIbMjDeaSZmwAlUyU8vRzYoIITE3IvafLmW3FA6FZmmYLB7pH4tEQnlBmCobWpuuT
M5E4qagv0jDDHp9fHT7ZHhGumx3DBLw3sH9JtzjbH_q96D5z5oVS2FSyX6MkSdvGbKuFgiBKDCSEp4CMoICL_YcOEAYQUn799Kw9mi-YnnXLkzTW11IcFadg
fvE3ggC1pfX2oIAIuXGjsiKfRNEqMVxPqUQ8ArGnTSQB06ydixVNoYL4y5ZcWXdZEHWpIYoyywFDeAuMHtZ69kgKvYAmkUXDP0OrLVf_TXYU5KpDLC7pFlNw
k6BY_wYPgM_NRvrQ42GrEYitC2WbAl2zox8VXhUFWHHMneXhQtk5nf6StpwnzlP9Ww-iZxTF9WLW6MLdojAQxl5WmLO0h3m6yynDeUbbEWP0ETeMXJsHJJ37
HKDAG4YRnin3uxl_uePREXOVwX-RoxDkvB4GaeTZuQvMeil3xRuB9LALLyEQhs_HUh3-94aJgFaPc3Zx_03vxMCW7oJzYhtfmQ7to_iVDNk__Ft3YPyX8xfp
-UdZh9yXmssxeEbd3q1_XCGZyrm-Cf-MU6J-mrwoa3zuoUBjydqjv_iYr_VLlo-OBvZl2-dVhp3uVkd5L_BtQrB-2m
}

sprite $APIGateway [64x64/16z] {
xTR5OSGm5411dyBHz5zjE8jVPhRUCeoPgjLLAf7_fhaayb8x_KJiUMh1yHPF_njQQFdvXnfy6aFiJrEN2qzDo_y9MPtQhB-4sBTT_tDuVfvFJsFw6UU_U6cG
V_NOqtDwfuTtwNNs9txwEAS_JRzKzPl-csNOmr--zlIFNWTvolvNZh-pUTfugCAWmSVw5EHye8CWzYVT493_jhcSd-7wTTPAfKy
}

sprite $LambdaLambdaFunction [64x64/16z] {
xPDLOaGn30Epy2Wqzpzj6UHYL8QThmNBKM8h_IXEdEW4PbSF4LyVlqtlqZVmzSfxzHrylV9-VNVrxpBmQF1GtwJFwPePai-c1ahoWLLQ-HJGLZumIIkV1jhA
1zwS8bfSVLDVGLH-YW3YweCtEZ7WfmZMMmFj3GOotDHFRqeHv5l3KEmKhN9tAqLQU7jts8mKgT4ZU2dIXr83ivMY8mGZrKjH77dsKoGriDWfWgvhPAS8mXfT
Wc40Y6iKLLmpU7nv_AGlw_M2C-X81HWxlkbAZUXrm7kjMc183vFCCIPwG5_XcQ8C0tfOuXpZNo_hOxvWp9f2u9a_zJ-df8O_VmOdJfm3
}

sprite $cognito [64x64/16z] {
xTK5ZiCm44RXlzo6tlrFk-0eev2byInl_Shm6OfArMer7BL1RWrvthZMMFX8t3Tiadg_9-RpTmn1Fz0gxacT7NxLw5kG6aWUAFNZ-OFUVDdwRHUs_k_sZDSz
VcVdFQcenmgjFxdpDLsvbtjuQ2hq_MbbNP1y-nUsTSqhzssPNmOeazUFpNwDcWBVp3nMv_NpREOUAFTpb1q07ddk-PzWj_I0Rw4P3pTDZSCTLD9cyn3mncCU
uo7VWV68Lq_Y4JzmJmE4-1n4_G0BVbAcmEVV5z1FLr2WbgcROjsIFkaVLQkz0W
}

sprite $informatica [300x73/16z] {
xTkBSgGg40PWciPB0_A__zkUCZXfEsDagDcpL_wzZh8qV8LAh8rx8UJTgncHrx16l7DJUGLhHDWvBxcDDRBY0-mLh46rx7zCafjOWmgy_-apcbY32bJlMcsi
GINrhvEWWJMeC1qRXu86rg32GqTo0sjGPNTa4jnY3IeixeZFkCKQL0YwVo-tM8CAvEn52EJj4cjGHJtcCshA5TQWmkmqKlulBAA_W0hidBq8-x5y2sgEMqah
_UbKcvbqGJyMfxNH03NiVch8U_z3gM3dARaRQmQM-p5l0B3z52j_MhmJ0FTk1AS4SseIA5RnBy6th2QW17B4vFxlp80M2K3-eLIm7ZwZWTLl9S3aVaeyW8vr
rKiLlvvjOVLRRO3_5LR4x7ya5MPdCzdpnRzjHG3ePrkrqqy5TZPKqC3gjYe_pOhUjA9RgesUC7C3gsb5tfErWdScvFdKn9wvxgZ-cwV6ff_MkYAl_PqwrLv3
27H5PNSCzYBimbAh9KPsRae0a2Qgnr9A0D97GXtV5B57mgaF4R_NZX-iBB8w5mG0OcrLFwIPr6MI3NlYerIC2K3y2Bj7DtkqwhRovv6m9kp9YwyzXed3zrG8
LvTC5vPQ2S0KSIJvUb9JduPXmoE9JzUETpuUp-K0H3UZPk-SvDnhbO4cyzLEIFSCjghKBZX_7HdxXSFtLBXWaDo3PQtc21IHkhJemgeI55cb7j7TAX6WLh9R
f5ZguqS0fDfh9hKgSLqZzlWhAmQIxhk0JOxMxEhPlTDLjiT0V20EtrCTxdu9viLC1vQr0hQFdZYY7YKYNm2cFSUU9tqqeQdEwR0gl3ClWUk20B1V6HHshGYi
VX-cw8FROs5oZtxak7i1OB-7ZDNyMTKlUDpJieJQ0QT3cpdGjrHrajKupbmR4j23PQtoqP2ItcPFpq4FG3u_r3Q7LGAMuqmuBJasjrK12kapIvlxv-UWMl6v
AZ-wreQKxDw911TXhRPddVQQQ-p1ibPy6YZuQSyWnwMfSakrCbkzK5UANcpRsPglHZ3NqzTMqLHbPJaLJ2qgaB6g3mMUaHE-9lChLb4F9s1Ig-kfJdK8rKhC
Gc43QdgzckfwOyMrkzOMi44bEkQdf0oJmaqhivAN-iaCP3QQrIWyhFWyzutEymXs2PbK8hcnMchLkoJ0trDXEZycMbwPsrP13yyNLgfffqwRcKumdpB0jjSQ
uccf4I3UM4LRLUCV7QmRuE-fu8rLAuNVjKgrXMcq7bPpdnND1PexgxfudnFIbSM2w-Jp_RET17hJAZ-zBWD4fzDXHNMp5J-IxgsAkLsPEPTOKtHTHLncqUd-
-dNbkwmYWDdh_QfxNKq0LYPplxh32WshbF5JxbVzLlfeQrkvf5KrMnsriRh1qcvZWqbNrLjMzZce5sM_rGo8CrQTpq5jgLPtMDf1H3EPtTjMkXmKfL2_bMv8
QiAzLT2gzboDrh_1qcfefdZtdbLDCZjeoaURVYjp1GaGxxx6oRRgLCzjzisyTtTOhDFje7h7odvbHl4OSB_LT9xgXBDLUBOAfgfW-TBIRsfrZRKv3Ki7rHjM
RlbyRKKXur3ejoATFSsd-qcglLFmvZfRJrKF5z754WhKwXfhCIT3xgJgjz8bdDTbVRmswhUgQwc-mGbB0QGWwX93YXjOhKpLWiF8rtS57EO8HBstNsF95ycv
GTLdfRSKWXd8X8lteiLQcHjl0VYvrzDeWzVsWXfZPPkdMeatNJKKhTK5Lfp8d5qwg3HpZBE-RrUJ6AVQhOYSw_WvOS-vUapfL8LJ4dTvJdjrl69Fdhtpf_PJ
-dmlpp6kMdKfHrLT77KSAziQrrWGB6p_Dq07rHlnp4pktP1dzdHns7_JF0Isfsm73ImaIPDt6euDgdydYgMHl0Owt-G7rSrhlonvzbSt-LAf1fP9ZAABoozt
L0CBvNoZPxcZ6bX0FEqYE6AxeHfOW61bLpCTL0FhMwqaQJPA8nRBHfBPHOn8n8sMD9VMM5cTtuypi79kK0si1jN0wgOQM6sgaLMwg0PMFzN0QbCDh0wgWTL1
DR0wg0PM1zN0wg0QM2zJZTJtUoF_0G
}

sprite $AWSCloud [64x64/16z] {
xT45TeGm003HYI1Tc_kVjXRore3LPsq-ChZo9pHDqqHrB4imqq4tBB82j6uwTcF10es0ca4pW1fA8Mi4agnJgJVMMj2HUmITPeoMRXHKxgB7MMs0GG-i2au0
xK0PZbzJrO55MW5HmH7SWHwlxvPvgHvLgYHB3mOgDJBBg_ELsYDrzVpQNXNOE2X76sNMzloNemvJCy07lpIjVpzKeEROYYMg6s37ByiTavbV1rKZ_vfgpxCi
c677dKQPe_6byxdlpKHPe9hMRwt8eaxL3NEYgj39Yi79BWNgcTb913BhaakuL--ro6FYngeFl5lJDCqN
}

sprite $controlM [100x39/16z] {
xPQ7RZCv30P7f2gbtU_zd_PALWZMFr8G8pwq6tUQm83V5ed_YCJBCItdnKn98_5IZZCFgRpMiH9PEfoDbymlSwu4DAcbBTNYbsbo08iT65F1BsDI1g1CjHSv
AD8mWAwu7DDoDY1Pikm9omx0BZz3wb9B5f9VZZSAB2r9HvCq4rH96Zn97ZgaPcp7B4joGeefAK8QLAbNgV4aLPACxPYGfe9G9KaBXZfIXnfFEcn8kKdjTbvb
JU8AR41Lvv3pD5KQ1dcgtHrnEUPsfFDv1rs7xo_1kwDf_J77gGoanC_9Eo9Rx-VLAbwb-ZW78MMFfqwigVH-_kvxoKLYgi2XWAQ1wGrxyfv8bgPnqLQlCqQ2
VcPeHu5oDh0n8umdM4UozUAR-td6ZkbrD6awhoNLmX-Osuzt6Idzn3bcx_seV4gEZugLJN8soJvHg1lWiTAdZlMr8zYK_ecYSj6CJ_3vfGDbBex1HxG_oZtw
z4jfqSE1TXohCAvMNptweyCLMwl-yHY9Ez7SyYp0dDtD3mTlArlIB0PrPlC-7XozZWn0vFQnWpkZ0h0SuW2mTMMrCzsfrVxWo7O0v45FtpfCl542Pdx_Fy_z
XSWxUBivcbtrQKp_tZ7tPsUtswEZE-n1SoMNVo3rQxuyO6O-8EvLNpT7_i0njkDuSvYR6tO0qpaCseUEBDwvse4oFdEKFSSjApi17ta0Llc8jjBLAeSM0Axq
djNvu30PG3HkZWaGidsAV4HJDRDn5808jweCdBSv3hQ3h68-0yYDYqlcSxT_Z9Mbo8atl4L907OLd7qRSdPpD6SNxpV7tSvF-9-_0G
}

sprite $callcenter [64x64/16z] {
xPO5pYin38J7TdXXxd_QdrQDMYzNyF0J5ipZ9FWj4Oinck0zh75X3BYFDBOWFqbaKd4JvQm0rF2558QxvXNGoaVaUC-1i069Gr31GhnLGgR0vLodPHv1huGF
Y3HNKOmaP_Ayb4W84rufP1G0cbbmp50GALuEHPwQUmW3wb4CPJmUde7fk4317ZQGYXhE6hoDL9RpZTajJovAFNDR1-Cik48WEGTu4WLNqSowoZxY1ihcinBS
mOkqL6mYNs35Ek2Ki49YvGyr2ZnEPklojP0bcgh5GXQ58xV3-Edbx0mZqtfJdwZL7w71rzl4sU-tGsOg7Cf9Nl8VzkS_K01PZMnm_TlJNw82YPFw318wmMSu
zVIK0SYCbOgEin7ctVsh0v1emCh1K7k84Hvfo_uhxT6EwbHjYqDDVXXzoWn818IsAIic64b6RAD1CEPk66XET2Ca1Jq_uCe0m9XmUqsL-cDgG1ctVZn1bn1j
wErworuPr_s7NB7NBaAPA4jNByVleqEZB8iKsALb59mnfuUZMI2LbKdg8waPf-IfPp8945f4b_AOSOfHDwwaIYpIFcSi6yUGKReWJh2dA8bD-yF1BeJtQwSZ
Mr1Z0uJryXlEFsRBCj3thZTH1QHHSHKbzU2RSwGow-kDBRX585jK-K9Z8mDkOuLSA8RtKFj2yRVod_zy0W
}


sprite $rgi [88x64/16z] {
pPS7bkGg34Kb18v8R_-hdG2SrjUOgL_sfBuTdMw9z3YcJmqdoINHD_AsR_dtACjw600m4MtupaQ_ICfRRIQhM8XeGJKpnV9Bqd80ZX2nOS3q4Cu7SAubIsf8
OQA4BZQaXwMkUYp25FXbhsnRPffHOKrRdrYN80racAeQyeCPaEW51TyfzoShqskuB9blQ-cpmJ_oAX6o99uBhjrk2EYnoaHQTaDdBq6oev4eia1nePRPe9kf
MhClv9mmm23_vsqfWft9IGUWXe6feQRerPTUHr5TB80Ye82yMQyDj1yg3XgaeJK5CEes8BtXZLWN5tyGusoj0CRH-ORNiAM1B0RhUXv3fbsq2nEnRE5pNtj3
tFCE0w38xKZHjSMJnj3WD-frhz-wTeiYtZ1Qe2XtlQMVs-aR6-mIhti_jz_r2knZP0uOe3zULpE3yKrlSYzNu3hj5OrqkzvsxlZkdUvUd1fqqxlvk37inIv-
QvvHWS-pzDmRw-MqeM5WzoezyW9wTgfXcB2GUoirP5t-2z_AoQ4zuzHe70Z8ZJph1mhbYNU7sWVwXlV2pZJr6Zwm6_MYSsGQnFxTeOqRtW3Jt7i0j-erh9nI
uj8iXYLuFOkbTAfxtriNHrW6itNXjzcDVCWZMbSQU3wyxULqzOw2tSCwoJDMD7ZgNMZY5MZpRhvCcxTCShJIpBl9p4lxA5ZYtd3CzjgPj-mqyNh1UzZC33cK
-zFzBK6kNY_GUvGz30P9mnX4xsaqzNh19tNMSOmUNrmmFdYZgxTWdNaRcyTwA1Wujkr0qtgvmSj0ddZZKgZUW16Ty3yw1D6x0ZBpne8BTKRB0S_Hzi35ozwA
cJV1Olnaz987fjvSzmwNU-lbTNo5MZZ9MzCr3C2UoBrGKstUCzJR2DvqpKjP5GFTmgAkQAJMJbyVB0sc89P621kMl7mZ-wtXtXvQXeL-EmiCKARVpGg3lb4m
F_328A-bakW67b5u9POYT9k4aIJb9z9b5Nh2tiM68pD5E6_dGwk_wIbWMv74tqcIbmseXUan0gWPO8f0NHBz4cdl0MAgLMqipvBerv7r10Pwh2Kn_IvO9ESi
YN-FyYi
}

sprite $iiab [124x96/16z] {
xTe5qkBgea3HbNnHmjzx_gDzxqfNSurgfOwnSLret5-fT-_cQVv7qmpCdmEUtFRqac-kNzzlQKz_5DklQ_iDxUatjESNs6_xRR_jjwtoMzbuWVsst_RRVjlp
hUitigUgE8vjNPTbNVhSibwzsAv3SuLnVTm_uMpZevRNsciisGBJFC-V-jpCI-tvd2Y2xRfk5PpnOdizsMBUOTblVMvuRaSGeqvEYAgWq02ijN1MNJpigWYk
UzNzFXTViKEkQ9k29aqKKw5c5lRem_g9Vs_fLWHRhN_lvElsIZh05njNB7sWOd7RWUNatzih25FLjG--Rd_iH3Lvs5KJEr7hiYnQWAeyu7NPPY3SLupjNdtL
DXBCtPSlzgp1LaMBFXxsbaUrdrrWD7jKFlgQhH8SvmT4-BlMc4kBlUmxP3qz2kSExk7HhRNRrspbQD5Eko9yIf06nH6jjeTXg_fCJFdtZdfkNmHtr8cf3WJh
Ek0kc37Auo-5Dl1Hkot_tVcwOKkwdPtRLVBuhxS2UgLjcFRh6XNLofHxrOR62-qwwZgGPG4k8ooTkbvecrYs4ra7CCzB85TjJ-sPvyqJmFJCRZNssyrSfZ3F
M_O3bMjStP_-npO4ZbPGLHnLw3O-UcORovZNjWj1rxcVEsuBTexZgTr4e4vGbBF6KLID9_OZ5TkzPLvhvjZsEcUcv_PEe6C3DOrI42hFxQ-tFxF7cc3lLb3r
I-tnpAOZg7j1KGfhR9LVrh_R2YD67lPMLTHLBxNd0JEgEfYgA3Hv_WTVLunOpGlpGOW6nck6BME6VOTWh4mVj9cY5TjhxC2jB_ZMHlCIIvjMhA-pDqSJx35k
6vUHoUYbzZ5ns7UWmrYPJfeFUkbdBjFkFDm63CjkEIxc-qfR-xdPNsG_cYV_ri0Ox-KER_jjl-q_rdg3ztgYj_sst_RR_kstRrctVTltlny1_tLf--PBVTr-
RqjrwrTtzvVktRjt_my
}

sprite $mulesoft [217x64/16z] {
tPk7tgKu2CKbpJwy_zDkSUxv6JoYsRwvJ8j2Clm_I89jy2MEUiYKPFWQcVGYU_WggdrPjXEkyy3f8Ok9a7ooCdIEjTnfIizHowggsTFAWTPhkCOdWz1dq5hY
CQjgwGihKBZSVDnwuehDITRNH8lmzjl8u6khyTGVbsZqZ4fb7dhXaggU8ZrfEad6ebfCGUNGTqF6NlhbBbHdZP9wue9ufQ8nxG2ieAo0p3T6H3Rr4h2Wf_XS
klzz8PCtVSmflDTCCJjW6GsNBDSgEGFDzEsRUO3ArKFMbxXGyY3_qAYbN7epz3s5i7CFLUURmv3nnMowrSne6F6vi1uo667edmRxf3rkJSGdknHloaB1mQ8k
MRnNgIulOFAdmM8L_KH9prK3v_PSPHR7nL491cKmSqx_D9ZjbroxpGL39aObSRcW-cV1ng51zWSmCTudsh52TNm52svnWkC_3pQqo0f36l2QYMSJRYj466ng
1Glft91Ip3TWUTsMz0ucuxfDuJPbIzqfNS36unm4mJvahQ9NyEEw0ri6ktz0LPdbAvX2dbDHx6waa6aO9Zl4g6hopTel6CggS90PB8x6kPBmux5WwG96qnSj
lqumtMO2mx_53WinJG8B32QVosjaHe0BBXYq6J56Cjp4x62GeK0PZdW42OStl_TE4WHx4QKDaX5IvzTOsmc31I0SHziGMy2IeXLfPYzP3DUbjV7YOUV_Rgjw
T-sFvf31uiyC7E1jQW332VOT8dTswN6v1zYFIqtcxMcX2GnhQpjOFGPDg8-JqOwnFsxG2D9gm2WPvrQm0CV3OTG49WG6aOGb8MFIcbBg4Mo78G2SUXx0puj7
08IsWM7C64CCCOPysb49kbIw_0OsgfB3J4OF1T69Kz5ip6rWXTEUoOA5I6zWy4sUIlgPS6TGKiJ-TZ1irqrWVabbHtDFHg-a2gULj8B1nfUVsyrCvLCpcDqJ
YOlNZlW0DhI2IHEONJpc1h1i9mybu-Iouby24qMhgQHg0SlMSTm9sHelD87fY9WIDBbWGqh9peMgX1mPZCdYDVylbJ6cm-w22LU1ll2j0GQ3M32fzeW33CvX
xPxWJaAohEP_HIEw9HLI0OA3-4x65z2DOEWxnwHQW-cI4vHP96AQwqUsZKlm53SCKKKCwYr7oiKtiiaQb1QmIBNV2VQ1lDqqfziT8D0MjAh-k2uArtLHNiXc
g3UwOSgfO2i4EudhIGhrQgf2d44NJXg4vMxlfUfC7yXOczWi365uEfV6ylk1o7bAHD3AuvWkVVCuPig1OipGdmQivyhJdTV2rn1JXu-HiX-nCfXoge_dI85o
aS0sivZ-pwNGikE2xHJbJf9HN33iCSJL1ncsz-TN2mfCkYBBJZJCnT3KvIj7AwcvJEf6shqjiFooryH-zCM5ouWMe_A5hvYE7RuwY-ap--f4v7q5RRbNPLJ0
7QFnD8hcAgZlJq36ACTXA3r_0lBz7-tmPrPpwZ5Klm8
}

sprite $kafka [48x48/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
0000000000000005CFFD7000000000000000000000000000
00000000000000AFFFFFFC10000000000000000000000000
00000000000007FFFDCFFFB0000000000000000000000000
0000000000000FFF5003EFF4000000000000000000000000
0000000000003FFA00006FF8000000000000000000000000
0000000000005FF700004FF9000000000000000000000000
0000000000003FFB00007FF8000000000000000000000000
0000000000000EFF7004FFF3000000353000000000000000
00000000000006FFFFEFFFA000007FFFFE60000000000000
000000000000008FFFFFFB000009FFFFFFF8000000000000
0000000000000003AFFC6000005FFFA7AFFF400000000000
00000000000000001FF4000000BFF60007FFA00000000000
00000000000000001FF4000000EFE00000FFE00000000000
00000000000000001FF4000000FFE00000EFE00000000000
000000000000002AFFFFB40000DFF40004FFB00000000000
00000000000006FFFFFFFFA02CFFFF747FFF600000000000
0000000000005FFFFFFFFFFCFFFEFFFFFFFB000000000000
000000000001FFFF9447EFFFFE50BFFFFFA0000000000000
000000000008FFF500002EFFE10003797300000000000000
00000000000CFFB0000007FFF10000000000000000000000
00000000000EFF70000003FFF20000000000000000000000
00000000000EFF80000003FFF20000000000000000000000
00000000000BFFC0000008FFF00000000000000000000000
000000000006FFF800004FFFE30005ABA500000000000000
000000000000EFFFC76AFFFFFF72DFFFFFC1000000000000
0000000000003FFFFFFFFFF9EFFFFFFFFFFD000000000000
00000000000004EFFFFFFF601AFFFE425EFF700000000000
0000000000000017CFFD820000EFF20003FFC00000000000
00000000000000001FF4000000FFD00000EFE00000000000
00000000000000001FF4000000FFE00000FFD00000000000
00000000000000001FF4000000BFF80009FFA00000000000
0000000000000003AFFC6000004FFFC9CFFF300000000000
000000000000008FFFFFFC000007FFFFFFF6000000000000
00000000000006FFFFEFFFA000005DFFFD40000000000000
0000000000000EFF7004FFF3000000131000000000000000
0000000000003FFB00007FF8000000000000000000000000
0000000000005FF700004FF9000000000000000000000000
0000000000003FFA00006FF8000000000000000000000000
0000000000000FFF5003EFF4000000000000000000000000
00000000000007FFFDCFFFB0000000000000000000000000
00000000000000AFFFFFFC10000000000000000000000000
0000000000000005CFFD7000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
}

sprite $talend [256x64/16z] {
vPg9akCe38QHk6t3__vlkvMWQbbJ3esdTx97lZdZWE5373QqSnHBBOdSQuZSks3ltWW__jJWd0lrTS49YEuTK2Z8xvCF5UoeyYYxiBice3Mm--E4V018xYrG
o0tOsSNW1logv8YZmRi_JGJGsflyUGVGSB0hv8HCBz8U0CZzQJ8QtXH_wTFzuL-r0kokuPoAVuD_VwF_ACp4VxO4KA7_cJ_4Ftate7qMOoxk5ZxyD_nLBCLf
B_VPhK8-xzZ-8_ukFCSzfU0SvnB8lI16jmINfqVzh_WxJYad6GQSIYHtJVQBwrZhwFyP_mV4waoX97QN55vSMl0VyhyWbCoJHU3_x2_uSjdPVVu4Vr4juMeE
_01_WTD52wJm2Vu2fH9eTGvSzwSdo_wIXINB329cfdcI9tD_XMA9j3u7gZ-m1-y5fv1FPSE3BKTFI_uKyWu0hKRl31mUU9iCDTAr38TKzmuSMwx6VqR8TZdq
PS7VGjgQ1nxqraTDm_V-b8wHu_cjVK8jUD3ecMoNP1reyIgKujmXgFySRvV3a4OWOqg19_vjS42C-5d39khelJMWq3V-OGU-iZnoPAUaHo5z8-UYINRHY-Ak
ZOZU-vg_u7FsPWxaB37UmtVnRnXPIMhs4DTwOAUfVnIj_X35yqCzDndGiJagQY_tjJs0goHG-KL_WNDMqvHEPMtymhy_QL-62SCU0sa1b9b_7EdxAKj3CVx0
5WzqAL0hnaxXaK2BNuw_mZ47tG_j6bxuMVormv9KOYiffTm0SGgl_Jsad9P2I1kan6JzEz3HOUZdSSBjzFLUIprknjyk1j48DdI-yZ-Ym1fCu6j1fJ0grL5V
-uinqiWK9CxmnlzXtu4z1Uz3XQ03YtPqQQVYYHvNA1h_PKA9n42tJRsjhVzKi-cKkzZmA_ye1NdjntRCPEs4rMicswzSGHjNAfz6XF5V9-HHRKDOydVa35xg
7bxvR-WgyiIBYhVnnn7CFgeP9K7oo8M9l_TkXbR1O5sj_vpwy6k8B_p3-3hR5RyDDnF_IcSrT4W-xVqo8SpyUMjjuuN7T8FUvhv_0bH6_KqWjVThcumrKEjY
nn_LaQPeTMIGplnbijdTTsoumF-MVz2PslXhuBJUUl49gx-Dh2oqwb-rYbD_7Zqh-ZcXGp5hs7r_F_Nted4vPhpwurV_UCx865Ituj-HGvmHOeEWDCHR_aJ4
pDxdcRzg6DBmZnF_SEx_mKPetl_xmZdNzgFuKyXrs_RzE5e3flxo-SY6NUQCLVzi5jdv_0SSVd6RmjBych-lC4pzYnPqaMVLlqehqinVy9xS55rUhX-0vlvS
lzu_-fEvVuKaK3HFkU4ljPdwh-Clef5M_3tGS2F-c_4tj6L_skJ3t-JlIuxubOCM_7deZvVPVQibfxhYVqrTzjSoVkxlI_4o1TlPRy6_3dNiwMkKnPNnVvGB
QhmJ_v_xa-VJFb11iriDSt-p3XMHd_lBPpEsB8l-xc_f_xoZfOUzi9zt6w9RyI-Z7Xiv9TvV_othyzzEF_4lECulUJw51g6mM_2NVjZiK8ahpt_Rp_oB3BjV
_VSx_XNjl9zGwFaSKsk9lBJ_hs_klExFCltx7_d7w-S_kkKVJ27Ptp__y4EchVjBw1hIZ_mPW-tIlotuIuyd9uJeViV_8lvfxXzbuu9_uk_QvViVRTP_7Ivk
oNyZs_zrhyS6MFtranqpbNxVNrThMnylpNBVV_7yIuUMzZVRAYHJ4uhnhsSzIK3EG7Vy6KswsMJlSPqKbZR8TE7sBB6sBYIRkMgSvNDmZkWyTZisVvBtfTCD
VvU_6a3FuSpPp1r2Mdz1IfvzBFeUBYxHC_kq0TtkL2UqaQIKlPBToqM9dedOZrE0UCUVE-GkU_H4MlQg__hfhoxrWt5ooVeWDWe-7jURdkhGQReJWerT1zg-
xqS7q1gsLNzpupPkCcvXDcwMoUocQ7cYsdeJ5mzfW8RdTJJixRmeC9eUq3Kz5EZI0dfot15M_RKLfMYfqt7efB1EZ4vOwm1cV0UOons5yaXWWsqd_GGqM1hi
aZ7prtIcw9sZ30bt0v_T4gpl1-T59i1SZb_dUrNNP3sUBNRFwBpziKUQnn_3Nqbw2pbF8mputk1VWp84hQozt3FBWtLllKaAIXr2A-7Kx0rAovxC-Nz3clWB
N03xobBGUjUyKuWzaylUBKFn-NwG0bzShYdGzSy2KKYvv1ZO6SYFV2L7l_IopioUdO5ZgTjsUcMXmTAY5n_r2kupIN7q_i_qr_UTmfyPVd837zq7Gja9b3xI
NzUH3_MdhnN4VIBwOr_UVIAq3--GtMV2M_BiSo7teL0iDGVt_-Gl
}


sprite $SimpleStorageServiceBucket [64x64/16z] {
pPO7hcih34KnffUi-O_sDvw4KCYvpbUxIotDFcRRsy7zMkGVr8l8jt4-fDA0JIifUB74XZpun2pXCOTFdSMiEOQWYn1YhfF5IDxT2Qla_gbI7zAVNmJtZdQ0
7EIdum6CjmmPQDVWUvt57LJewgneWtgaXEo-8KDqcqPptr4ORZCexZiohoCRoNr3F0L8GFjEF_Af7p2YDmJxE81JFuKrkZC7_nIxtC584Dp6WpejB7f9GRs8
sqRs6bBfBAew3zvjPAKJpODdnfhm0CUilaXk8HfpuqRBKMNhVyxl7e1TSOYBi4-pszylx-tiv-rwREppRhOU1hRUczsF4yazt_9wq7l2amfNP-hRuo1Uovpx
bu_7xTS5md_ajmo9wKxAjSwu9_QWKDyolkw6KKa0xP1dx6eD3PGuWPds3u1qKVGpeGCK_PCGOEYbev_HkbQCh1ytE3i6mJtZqrnAI03HUKPComOD5O09padZ
9QUZ3FZOLueIoo5PPZWRFhvOZF_fO2WnrvhaRA1ywLwBWvt1lJkfZNkf49sDkrIDx6oaQwiopRnywpKhpi0ULQE3hKgfjO42Ql_u_Y1xMVQ33fAnVLZQiZ6j
whNKBNIoUIojEfssiBlNi8BjHfzq_tDuXy-DfJoNe8M7FH4cG0d-q-Ln0gyZ_FPF1uoIOb3r8k9LmxuypYZk4PywdnX9dG7nCTLvkpmQsNV8_n1nlvY_0G
}

sprite $alb [64x64/16z] {
pPS7biCW34HDaN2Bv_wdJIDworWfRBREAodmAM80CVndXH1Z26-XKSO5DosZnC_1kc6dhNGtaPVQQv4SpyfIRd_a7ZfTAvT4qmwfN5j8BoCsKaTkMEFpQEO3
T-A7jZsRX0BGuUqA8x2yY79SWF51sGHCuMM0BhKUzJv-zEAqnbqzFxMn-UwbJKVg8tyRbl6oKyjCGDvFQyCIMdxOgUN3WYsuoSUXbn_YFWJ9Yb_pLe5Sjc0P
kdaFP6kkcqz0vjQwUOz4QgoFpqt05PlpKjx9UMP3SLzx_6Sgi4vZZHv5nylNiGa8y6ZR9SEy0Y3clVdXTYTRicRpu8Bo3bzi1Uj0I79J0OfzTtK0cqZoHLxY
OnE8xry_uoFFiTz_ndsLz-FlvzDzNgTfMe5fAirIJHEmdWkK-U3NBv9XdPqZhv_vX_XvEcjkzdJ--2yw_vX_NLI83rR6_kNzqy_R_Z4azVCSVZu_udgxwi9i
dZKlpo5P8PqVT7wfMJMZQhiqNfMB5LAdT7ug3Y9IUHMPWClgJY9wvLSHEK3f_AJ3MB5MgzKPQ-MrHgEkrmernDqVtJpV7zOQyx7b8_C6yFtfurTv5p-xFztz
BQWIS_nyiLbLKYka-vlpXvGlIlObXtD9vlyIvG-SltJAyXUVFtN9vq-FyxAEUb_D7x-UltuzV_vw_lxrzyFNtozVVpzz_VtszVUZVx_-Pvq
}

sprite $kms [64x64/16z] {
xTC5GiL040JHZYzQzpyjJcEHOHPdwqlqnQC_LQi5G4dY4ro6stL0oV2rYJW_VJdPlOiNq8iWIjTNNo3Z0OybEQGzJ1ACkcbA-USJGvKVw18UttfGlBdo-ddj
2Jfv3YkDkzw1rZsX1p2wdkjXXSUzPXlpiBUQ_Gual4RONIMsqF_uN18UmCEW1tkG5auVXWIykRt0GmUxFBr_-_pv3w2ww_znznzWPRZlOQZmFVIgE7v0DRw3
CUKTZ3x_pUBNVxqnuWFzFEzJBsa_0g1yvjauqw-erRe6
}

sprite $EventBridge [64x64/16z] {
xPQ7pkD028I7kalU_tslB3eX6UUyVs_vqWjcWB7mxPFnu84pIEAvqI5OZ6V66-0n1VHC1RGo1yEV9n-8bA4f1_-m9yKhx12FUTk1L-BP6hZRaGcmAI17OGJT
6_yTjGDWa5nN4Qucu5uP5hxPHk_vBQPkzj5QkmIMBxebW8u3fqmyghBEy4CR5wc4Sw8EkP-KOIMtq7GKH-awnQleKNsQ-JO0DYDmR3Gz6DKcpP87NTXuAImb
xRZXgdTTM9xlupVqkZe2QKfgcFrVtL_HbFIiaRzrUevpRGPwvVZdwtz-_ru-luw26AJH_DDyUKuW6MV-JHo8dTNJpv-4uPUh9ry41PT4Z__9JxcmF4mndh5w
MlilOLYDiOt_cW68AQ1drjnUFMTY1MpgiRDwzAnR4_khHz452A0cmDpR7DBhd-N3AoQErnm6hG5VOyTuXLNyCt1mh39eDwAtP8QddkSmi7Z9LIc1_VQfUF3W
Dm
}


sprite $eis [100x42/16z] {
xPQ7ZWCX34IfMo7p_rzxpI1n8vnYvTHkdnfhHdvRdRZ_oaME8wcNKumf_ChXcrqE0ZK9PJzsVA_YH05cB2ifvmeyTUdvlDaScI9AauJJkU1j3ZnmUDenE43S
vZqEbh0ZBy8QL4UMfxk2xyO6uO53B-iHpjuuPdSeqT0MwtiT74sKipbq1Iqj3bsooEV_9aUTEjAIynAVQHOrnoZHR_MAaSGX43F7YeRcE24iBMPmk1CD7dYz
TQVAiSNX4kyB6OpDmJd7HOop9CdWCZWKYKoFVG5ylwm8e03nrNUN9Ugy1O0gbsLqk9KS_BvAePLj3fOaK4_O7LpbCRQrHS0tlczO7N4ebpxA-t2dwub6Hm0F
MVNP0qP7ahB-Wn-7s47D_ClFO_OrQLyNcCGf3w3isxgUOCSE1NOmx8ZJm8v7EDrniYEh_y0EsgZFEWexjFD31XCffZcs-_SgZ1yBc9NUiB_Wuk8J
}

sprite $as400 [75x75/16z] {
xTG7aeD838NXNr8duhl_RHSmU65S4xmvy4rewxK9ebJmVtMxtMwUuf2Ck30siKlEBbsJNTEl0bqDmKA7cOUiG-F4Ji2ktAzVUJs6FqUzD3Zfembc7KQk_Qbo
abezDAVKZvfnAHQvFUl4dyPRhQsmYxNABAnjjtg4crCVpNZXMdJiaXRrcSilZoUWryxuCrcAI76g5ccrhgVmKVkox5klGekHNTPP-nWMFJcltCpjNBtEz_QL
bRljXSChMrshmpa4ss4hNhaM0xkait9gCDcpwyyQjBn8xBpaasBFi3ZfoFBAWBz-sgcNQM-npt-2sZwRzdbMOvSqpQeiR98cfKSuRvzwQLR0y2TFUohveMoF
i-IhKrWSU2wR4b-ysryPscMWannu_zr-3LcjooNwwQdyvJYx7lNp1ZEBIz4xdpKOvVA4By9O7TlEuXe5lzVDKc8LjTR49XTW7ua8LXxEjvAK7yiaDLPhO590
bZGQLErxN-gb3j1WM5C2Ga0d1QR1aogkQbM9hxbga-5gW6K7-WPvo0gI4emZHOwhyhKi3sKOr9TWPGfiJOEiW7wYoZ3rV6sSG3rufqKro8BM23bL3arMPs0O
-LAecVTom2AFgg2AAyZA50LqeWgO1hvKjIbitPb6N4xMObGAfUrkojPWuqlJc59azIuvX1fr05l2geflVnr9YQJCLv8gYrwHj35JEhO2cXO1WsR9-4eKVoo1
vrAIOPa7omQaKdmhIZPkjzljzWi
}

sprite $microservices [100x100/16z] {
xPdPekii28K5r2YYw_sVzX_2QJEqkzdjIUxApHxr2seNBXBEYszyuninNatW0bIvaa0JK0fGw3946h0OGZGWNqEGTfywOuQT7WMOQBrezNG40PrNUzy1FfzX
vebu6iq6dSyeD05ntdiWKy4LZ11OeI8DbKEuYX521D0bX2iPWQo5S34Zg1uoleoUrWp1NpAugcoBHfF9HTqPN84akjKiqShlA3XGU1bSOHoapegbwXBFWSsf
IsLP9EqWKaUNMMJfZfoNoKLTMnfeulzwdvGoe1o1djvGy3JGemzU7YvXZhIax8yIEtfq59eSRGHGQ1clB53UhEDkFRX1M9UYHGLukIqqOB8Qhu38_Z7s4x00
kiAAuPKaSzyyPGBma7XwM731hdozP11Qlgzs179zP9WzCag2ZtBTLxnaQA024vTn3jCZezQ7x37THecXKAW733zQPSA8is0yC5fxnl3fgnygFMPumYvAlyt3
H_c27UVX_zN3JmoYdnZ1QZY58Qho4wF_OUXRZFsUSt4fUy4uoeFHw4KUb0Vc67azYQ1k6FGw3uF5XS454A55u06eY09eyJv6P41bOOYYls04_bCbwd1zgymm
kGayO6a-G8QxGn1plIhi32x-_P4gJbHxYEQ7FGvKdgNkflQEzn9ICU9DzSbgoF2S3Y8QpBek2ZvrJZxdVlCJZxnGMxUsZ3g8lAze32mIln9bC7rK1xq8U0bO
CspFQEZWZ-gv1qlOCMf3vSssjRgt1_8E8bJi6J7axPxd4FUCNjzYz3qZUHcDNbdcWfnEPlZauju0AewwWE7p-lSNCWAPKRYO4LJ3IGnymXX_VQwE6VOMW-MJ
F8JVGKnRUUQ1wP4nxHXSfbz3wBacofOX2e1evoWoXUFmSXV5qDDjS9T5svsnQFj4TqTX4hr07eLKU0hP_v_IGANLKwgkCgMAaSYVAtio1osqvMQ_V2ymMTQc
n_yPiGFGfTRIob5mFQYrrD5bKo8WiYwGW9efDkqhaOwscbNwQsymNdk3F80nW97ttY2jJioXDvZk_o-6gVxc3YTGlphSB68xkYToXOaNEddY3QJMPtTHiNaV
lITKNpEQ9r2ofrCWuS2hESEzQK6FlxtlkfTzpgZbASFFOJx76_paSLpRps6eXWkymRbvCDfX7Za_yRNlvD5HPUSD-BW7C51uOKWzy0O5c7Zn1igywsNadNwp
mdiPv0oUZhs1A913xHJDHIcjvILsQFKFmQOd50qzafNVUeC4QElwq5joVfnhh3xjBVMcGFgiHyOAay35iJvXuI2sNaTwqnkmDjdv7avhhFVwTZLFcYC_3jew
4B9htXjqv6NFHh_YlS54tgZve-1NzP15KPaBJ2v-Rp2GBdzlqEdRqpzYJDSpOB9ci873sU5tJ6UuOeNJm-_DD3DIHuiN8FmARwcfL23HbU-sk_VBBmnHG3bS
72c5y-8Rt_Z6lm
}

@enduml
