@startuml
    '!define BASEPATH https://raw.githubusercontent.com/SergueiVM/resources/master
    '!define BASEPATH https://raw.githubusercontent.com/SergueiVM/resources/refs/heads/feature/switch-type-diagram-flag
    !define BASEPATH .

    ' Si se ha declarado la variable
    '!define SECUENCE_DIAGRAM
    !if %variable_exists("SEQUENCE_DIAGRAM")
        !include BASEPATH/plantuml/c4model-sequence.iuml
    !else
        !include BASEPATH/plantuml/c4model-component.iuml
    !endif
@enduml