@startuml
!define BASEPATH https://raw.githubusercontent.com/SergueiVM/resources/master
!include BASEPATH/plantuml/c4model.iuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml

@enduml