@startuml
!define BASEPATH https://raw.githubusercontent.com/SergueiVM/resources/master
!include BASEPATH/C4_Sequence.puml


' Rewrite deployment Nodes as Boundaries
' Boundary($alias, $label, $type="", $tags="", $link="", $descr = "")

!unquoted procedure Deployment_Node($alias, $label, $type="Node", $descr="", $sprite="", $tags="", $link="")
Boundary($alias, $label, $type, $tags, $link, $descr)
!endprocedure

!unquoted procedure Deployment_Node_L($alias, $label, $type="Node", $descr="", $sprite="", $tags="", $link="")
Boundary($alias, $label, $type, $tags, $link, $descr)
!endprocedure

!unquoted procedure Deployment_Node_R($alias, $label, $type="Node", $descr="", $sprite="", $tags="", $link="")
Boundary($alias, $label, $type, $tags, $link, $descr)
!endprocedure

!unquoted procedure Node($alias, $label, $type="Node", $descr="", $sprite="", $tags="", $link="")
Boundary($alias, $label, $type, $tags, $link, $descr)
!endprocedure

!unquoted procedure Node_L($alias, $label, $type="Node", $descr="", $sprite="", $tags="", $link="")
Boundary($alias, $label, $type, $tags, $link, $descr)
!endprocedure

!unquoted procedure Node_R($alias, $label, $type="Node", $descr="", $sprite="", $tags="", $link="")
Boundary($alias, $label, $type, $tags, $link, $descr)
!endprocedure


hide footbox

@enduml