@startuml
    !define BASEPATH https://raw.githubusercontent.com/SergueiVM/resources/master

    ' Set !define LANGUAGE es (or en) before including this file.
    !if %variable_exists("LANGUAGE")
        !$language = %lower(%get_variable_value("LANGUAGE"))
        !include BASEPATH/plantuml/lang/lang-$language.iuml
    !endif

    '!define SEQUENCE_DIAGRAM
    !if %variable_exists("SEQUENCE_DIAGRAM")
        !include BASEPATH/plantuml/c4model-sequence.iuml
    !else
        !include BASEPATH/plantuml/c4model-component.iuml
        !if %variable_exists("DYNAMIC_DIAGRAM")
            !include BASEPATH/plantuml/c4model-dynamic.iuml
        !endif
    !endif
@enduml